#!/usr/bin/env node
const assert = require('node:assert/strict');
const { execFileSync, spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

const root = path.join(__dirname, '..');
const productName = 'AI PagePolish by PageTweaker';
const dev = process.env.PAGE_TWEAKER_SMOKE_DEV === '1';
const binary = dev ? path.join(root, 'node_modules', 'electron', 'dist', 'Electron.app', 'Contents', 'MacOS', 'Electron') : path.join(root, 'dist', 'mac-arm64', `${productName}.app`, 'Contents', 'MacOS', productName);
const launch = (args) => spawn(binary, dev ? [root, ...args] : args, { stdio: 'ignore' });
const fixture = path.join(root, 'test', 'fixtures', 'selector-scope.html');
const secondFixture = path.join(root, 'test', 'fixtures', 'navigation-second.html');
const imageFixture = path.join(root, 'src', 'app-icon.png');
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'page-tweaker-smoke-'));
const port = 9338;
let app = launch([`--remote-debugging-port=${port}`, `--user-data-dir=${profile}`]);
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const windowPosition = (expectedPid) => {
  const script = `import CoreGraphics\nimport Foundation\nlet windows = CGWindowListCopyWindowInfo([.optionOnScreenOnly, .excludeDesktopElements], kCGNullWindowID) as! [[String: Any]]\nfor window in windows {\n  if (window[kCGWindowOwnerPID as String] as? Int32) == ${expectedPid}, let bounds = window[kCGWindowBounds as String] as? [String: Any], let x = bounds["X"], let y = bounds["Y"] { print("\\(x),\\(y)"); break }\n}`;
  const output = execFileSync('/usr/bin/swift', ['-e', script], { encoding: 'utf8' }).trim();
  return output || null;
};
const dragNativeWindow = (position) => {
  const [windowX, windowY] = position.split(',').map(Number);
  const startX = windowX + 120;
  const startY = windowY + 30;
  const script = `import CoreGraphics\nimport Foundation\nlet start = CGPoint(x: ${startX}, y: ${startY})\nlet end = CGPoint(x: ${startX + 100}, y: ${startY + 80})\nCGEvent(mouseEventSource: nil, mouseType: .mouseMoved, mouseCursorPosition: start, mouseButton: .left)?.post(tap: .cghidEventTap)\nThread.sleep(forTimeInterval: 0.1)\nCGEvent(mouseEventSource: nil, mouseType: .leftMouseDown, mouseCursorPosition: start, mouseButton: .left)?.post(tap: .cghidEventTap)\nThread.sleep(forTimeInterval: 0.1)\nCGEvent(mouseEventSource: nil, mouseType: .leftMouseDragged, mouseCursorPosition: end, mouseButton: .left)?.post(tap: .cghidEventTap)\nThread.sleep(forTimeInterval: 0.2)\nCGEvent(mouseEventSource: nil, mouseType: .leftMouseUp, mouseCursorPosition: end, mouseButton: .left)?.post(tap: .cghidEventTap)`;
  execFileSync('/usr/bin/swift', ['-e', script]);
};

async function poll(check, timeout = 12000) {
  const started = Date.now();
  while (Date.now() - started < timeout) { try { const value = await check(); if (value) return value; } catch {} await delay(150); }
  throw new Error('Timed out waiting for packaged app state.');
}

async function connect() {
  const target = await poll(async () => (await (await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find((item) => item.type === 'page' && item.url.includes('/src/index.html')));
  const socket = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { socket.addEventListener('open', resolve, { once: true }); socket.addEventListener('error', reject, { once: true }); });
  let id = 0;
  const pending = new Map();
  socket.addEventListener('message', (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); });
  const command = (method, params = {}) => new Promise((resolve, reject) => { const requestId = ++id; pending.set(requestId, { resolve, reject }); socket.send(JSON.stringify({ id: requestId, method, params })); });
  const evaluate = async (expression) => { const response = await command('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (response.exceptionDetails) throw new Error(response.exceptionDetails.text); return response.result.value; };
  return { socket, command, evaluate };
}

(async () => {
  let client;
  try {
    client = await connect();
    const { command, evaluate } = client;
    process.stdout.write('Smoke connected to packaged app.\n');
    const expectedVersion = `v${JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version}`;
    assert.equal(await poll(() => evaluate(`document.querySelector('#version').textContent === ${JSON.stringify(expectedVersion)}`)), true);
    const initialWindow = await poll(() => windowPosition(app.pid));
    dragNativeWindow(initialWindow);
    await delay(350);
    const movedWindow = windowPosition(app.pid);
    assert.notEqual(movedWindow, initialWindow, 'The draggable title bar did not move the native window.');
    process.stdout.write('Native window drag passed.\n');
    assert.equal(await evaluate(`document.querySelector('#empty').hidden`), false);
    assert.match(await evaluate(`document.querySelector('#empty').textContent`), /Drop a page or image here/i);
    assert.match(await evaluate(`document.querySelector('#empty').textContent`), /Drag ZIP into AI chat/);
    assert.match(await evaluate(`document.querySelector('.empty-bookmarklet').getAttribute('href')`), /^javascript:location\.href='page-tweaker:\/\/open\?url='/);
    assert.equal(await evaluate(`document.querySelector('#back').disabled`), true);
    await evaluate(`(() => { const address = document.querySelector('#address'); address.value = ${JSON.stringify(pathToFileURL(fixture).href)}; address.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Click an element')`));
    await evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('#interactive-button').click(); true")`);
    assert.equal(await evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('#interactive-button').dataset.clicks")`), '1');
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Hold Option')`));
    await evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('#interactive-button').dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, altKey: true })); true")`);
    await poll(() => evaluate(`document.querySelector('#selection').textContent.includes('button')`));
    assert.equal(await evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('#interactive-button').dataset.clicks")`), '1');
    await evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('h1').click(); true")`);
    await poll(() => evaluate(`!document.querySelector('#selectorBar').hidden`));
    assert.equal(await evaluate(`document.querySelector('#text').value`), 'First heading');
    assert.equal(await evaluate(`document.querySelector('#text').value.includes('<span>')`), false);
    assert.ok(await evaluate(`document.querySelector('#stage').scrollWidth > document.querySelector('#stage').clientWidth`));
    assert.match(await evaluate(`document.querySelector('header strong').textContent`), /AI PagePolish by PageTweaker/);
    const choices = await evaluate(`[...document.querySelectorAll('[data-scope-key]')].map((button) => button.textContent)`);
    assert.equal(choices[0], 'This element');
    assert.ok(choices.some((label) => label.startsWith('All h1')));
    assert.match(await evaluate(`document.querySelector('#scopeSummary').textContent`), /only this element/);
    await evaluate(`(() => { const input = document.querySelector('#text'); input.value = 'Live <strong>PageTweaker</strong><br>heading'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('h1').innerHTML")`).then((html) => html === 'Live <strong>PageTweaker</strong><br>heading'));

    await evaluate(`[...document.querySelectorAll('[data-scope-key]')].find((button) => button.textContent.startsWith('All h1')).click()`);
    await evaluate(`(() => { const input = document.querySelector('[data-style="font-size"]'); input.value = '30'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('2 elements')`));
    await evaluate(`(() => { const input = document.querySelector('[data-style="margin-top"]'); input.value = '18'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).marginTop")`).then((value) => value === '18px'));
    await evaluate(`(() => { const input = document.querySelector('[data-style="padding-left"]'); input.value = '24'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).paddingLeft")`).then((value) => value === '24px'));
    await evaluate(`document.querySelector('[data-reset-style="margin-top"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Reset only margin-top')`));
    assert.equal(await evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).paddingLeft")`), '24px');
    assert.equal(await evaluate(`document.querySelector('[data-reset-style="font-size"]').classList.contains('modified')`), true);
    assert.ok(await evaluate(`Number(document.querySelector('[data-style="font-size"]').max)`) <= 40);
    assert.equal(await evaluate(`Number(document.querySelector('[data-style="line-height"]').max)`), 2.5);
    assert.equal(await evaluate(`Number(document.querySelector('[data-style="letter-spacing"]').max)`), 8);
    assert.deepEqual(await evaluate(`document.querySelector('#page').executeJavaScript("[...document.querySelectorAll('h1')].map((element) => getComputedStyle(element).fontSize)")`), ['30px', '30px']);
    await evaluate(`(() => { const input = document.querySelector('[data-style="color"]'); input.value = '#ff0000'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('color')`));
    assert.equal(await evaluate(`document.querySelector('[data-hex-for="color"]').value`), '#ff0000');
    await evaluate(`(() => { const input = document.querySelector('[data-hex-for="color"]'); input.value = '#00ff00'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).color")`).then((color) => color === 'rgb(0, 255, 0)'));
    await evaluate(`(() => { const input = document.querySelector('[data-style="font-weight"]'); input.value = '400'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).fontWeight")`).then((weight) => weight === '400'));
    await evaluate(`document.querySelector('[data-reset-style="font-weight"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Reset only font-weight')`));
    assert.equal(await evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).fontWeight")`), '700');
    assert.equal(await evaluate(`document.querySelector('[data-style="color"]').value`), '#00ff00');
    await evaluate(`document.querySelector('[data-reset-style="font-size"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Reset only font-size')`));
    assert.equal(await evaluate(`document.querySelector('[data-reset-style="font-size"]').classList.contains('modified')`), false);
    assert.equal(await evaluate(`document.querySelector('[data-reset-style="color"]').classList.contains('modified')`), true);
    assert.equal(await evaluate(`document.querySelector('[data-style="color"]').value`), '#00ff00');
    assert.deepEqual(await evaluate(`document.querySelector('#page').executeJavaScript("[...document.querySelectorAll('h1')].map((element) => [getComputedStyle(element).fontSize, getComputedStyle(element).color])")`), [['22px', 'rgb(0, 255, 0)'], ['22px', 'rgb(0, 255, 0)']]);
    await evaluate(`(() => { const input = document.querySelector('[data-style="font-size"]'); input.value = '30'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('font-size')`));

    await evaluate(`document.querySelector('[data-breakpoint="mobile"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Mobile preview')`));
    assert.equal(await evaluate(`Math.round(document.querySelector('#page').getBoundingClientRect().width)`), 390);
    assert.deepEqual(await evaluate(`document.querySelector('#page').executeJavaScript("[...document.querySelectorAll('h1')].map((element) => getComputedStyle(element).fontSize)")`), ['22px', '22px']);
    await evaluate(`document.querySelector('[data-breakpoint="desktop"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Desktop preview')`));
    assert.equal(await evaluate(`document.querySelector('#status').dataset.captureError || ''`), '');
    assert.deepEqual(await evaluate(`document.querySelector('#page').executeJavaScript("[...document.querySelectorAll('h1')].map((element) => getComputedStyle(element).fontSize)")`), ['30px', '30px']);

    const secondUrl = pathToFileURL(secondFixture).href;
    await evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('#next-page').click(); true")`);
    await poll(() => evaluate(`document.querySelector('#page').getURL() === ${JSON.stringify(secondUrl)}`));
    assert.equal(await evaluate(`document.querySelector('#address').value`), secondUrl);
    await evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('h1').click(); true")`);
    await poll(() => evaluate(`document.querySelector('#selection').textContent.includes('h1')`));
    await poll(() => evaluate(`document.querySelector('#back').disabled === false`));
    await evaluate(`(() => { const input = document.querySelector('[data-style="font-size"]'); input.value = '31'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).fontSize")`).then((size) => size === '31px'));
    await evaluate(`document.querySelector('#back').click()`);
    await poll(() => evaluate(`document.querySelector('#page').getURL() === ${JSON.stringify(pathToFileURL(fixture).href)}`));
    await poll(() => evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).fontSize")`).then((size) => size === '30px'));
    assert.equal(await evaluate(`document.querySelector('#page').executeJavaScript("getComputedStyle(document.querySelector('h1')).color")`), 'rgb(0, 255, 0)');
    process.stdout.write('Browser Back navigation, multi-page isolation, and restoration passed.\n');

    await evaluate(`window.confirm = () => true; document.querySelector('#reload').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Click an element') && document.querySelector('#selectorBar').hidden`));
    assert.deepEqual(await evaluate(`document.querySelector('#page').executeJavaScript("[...document.querySelectorAll('h1')].map((element) => getComputedStyle(element).fontSize)")`), ['22px', '22px']);
    await evaluate(`document.querySelector('[data-breakpoint="mobile"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Mobile preview')`));
    await evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('h1').click(); true")`);
    await poll(() => evaluate(`!document.querySelector('#selectorBar').hidden`));
    await evaluate(`(() => { const input = document.querySelector('[data-style="font-size"]'); input.value = '27'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('font-size')`));
    await evaluate(`document.querySelector('[data-breakpoint="desktop"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Desktop preview')`));
    assert.deepEqual(await evaluate(`document.querySelector('#page').executeJavaScript("[...document.querySelectorAll('h1')].map((element) => getComputedStyle(element).fontSize)")`), ['22px', '22px']);
    await evaluate(`document.querySelector('[data-breakpoint="mobile"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Mobile preview')`));
    assert.deepEqual(await evaluate(`document.querySelector('#page').executeJavaScript("[...document.querySelectorAll('h1')].map((element) => getComputedStyle(element).fontSize)")`), ['27px', '22px']);
    await evaluate(`document.querySelector('[data-breakpoint="desktop"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Desktop preview')`));

    await evaluate(`document.querySelector('#markupTab').click()`);
    await evaluate(`(() => { const input = document.querySelector('#markupExplanation'); input.value = 'Move the marked block closer to the heading.'; input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    assert.match(await evaluate(`document.querySelector('#markupSaved').textContent`), /Ready to attach/);
    const box = await evaluate(`(() => { const box = document.querySelector('#markup').getBoundingClientRect(); return { x: box.x, y: box.y }; })()`);
    await command('Input.dispatchMouseEvent', { type: 'mousePressed', x: box.x + 100, y: box.y + 100, button: 'left', buttons: 1, clickCount: 1 });
    await command('Input.dispatchMouseEvent', { type: 'mouseMoved', x: box.x + 150, y: box.y + 140, button: 'left', buttons: 1 });
    await command('Input.dispatchMouseEvent', { type: 'mouseReleased', x: box.x + 150, y: box.y + 140, button: 'left', buttons: 0, clickCount: 1 });
    await evaluate(`document.querySelector('[data-markup-tool="arrow"]').click()`);
    assert.equal(await evaluate(`document.querySelector('[data-markup-tool="arrow"]').classList.contains('active')`), true);
    await command('Input.dispatchMouseEvent', { type: 'mousePressed', x: box.x + 180, y: box.y + 110, button: 'left', buttons: 1, clickCount: 1 });
    await command('Input.dispatchMouseEvent', { type: 'mouseMoved', x: box.x + 210, y: box.y + 150, button: 'left', buttons: 1 });
    await command('Input.dispatchMouseEvent', { type: 'mouseReleased', x: box.x + 210, y: box.y + 150, button: 'left', buttons: 0, clickCount: 1 });
    await poll(() => evaluate(`document.querySelector('#strokeList').textContent.includes('Markup 1 · 2 strokes')`));
    assert.equal(await evaluate(`document.querySelectorAll('#strokeList textarea').length`), 1);
    assert.equal(await evaluate(`document.querySelector('#strokeList textarea').value`), 'Move the marked block closer to the heading.');
    await evaluate(`document.querySelector('[data-color="#64d7ff"]').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Color changed')`));
    await command('Input.dispatchMouseEvent', { type: 'mousePressed', x: box.x + 220, y: box.y + 120, button: 'left', buttons: 1, clickCount: 1 });
    await command('Input.dispatchMouseEvent', { type: 'mouseMoved', x: box.x + 250, y: box.y + 160, button: 'left', buttons: 1 });
    await command('Input.dispatchMouseEvent', { type: 'mouseReleased', x: box.x + 250, y: box.y + 160, button: 'left', buttons: 0, clickCount: 1 });
    await poll(() => evaluate(`document.querySelector('#strokeList').textContent.includes('Markup 2 · 1 stroke')`));
    assert.equal(await evaluate(`document.querySelectorAll('#strokeList textarea').length`), 2);
    const markedPixels = await evaluate(`(() => { const context = document.querySelector('#markup').getContext('2d'); const scale = devicePixelRatio; return [...context.getImageData(80 * scale, 80 * scale, 100 * scale, 90 * scale).data].filter((value, index) => index % 4 === 3 && value > 0).length; })()`);
    assert.ok(markedPixels > 0);
    await evaluate(`document.querySelector('#page').executeJavaScript('scrollTo(0, 300)')`);
    await delay(250);
    const stalePixels = await evaluate(`(() => { const context = document.querySelector('#markup').getContext('2d'); const scale = devicePixelRatio; return [...context.getImageData(80 * scale, 80 * scale, 100 * scale, 90 * scale).data].filter((value, index) => index % 4 === 3 && value > 0).length; })()`);
    assert.equal(stalePixels, 0, 'Markup stayed fixed to the screen instead of moving with the page scroll.');
    await evaluate(`document.querySelector('#page').executeJavaScript('scrollTo(0, 0)')`);
    await delay(200);
    await evaluate(`document.querySelector('#helpTab').click()`);
    assert.equal(await evaluate(`document.querySelector('#helpPanel').hidden`), false);
    assert.match(await evaluate(`document.querySelector('#helpPanel').textContent`), /A handoff is simply one file/);
    assert.match(await evaluate(`document.querySelector('#bookmarklet').getAttribute('href')`), /^javascript:location\.href='page-tweaker:\/\/open\?url='/);
    await evaluate(`document.querySelector('#bookmarklet').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('Chrome launcher copied')`));

    await evaluate(`document.querySelector('#export').click()`);
    process.stdout.write('Creating AI handoff file.\n');
    await poll(() => evaluate(`!document.querySelector('#handoffReady').hidden`), 20000);
    const handoffPath = await evaluate(`document.querySelector('#handoffPath').value`);
    assert.equal(fs.existsSync(handoffPath), true, 'The handoff ZIP was not created.');
    const archiveContents = execFileSync('/usr/bin/unzip', ['-Z1', handoffPath], { encoding: 'utf8' });
    assert.match(archiveContents, /START-HERE\.md/);
    assert.match(archiveContents, /handoff\.json/);
    assert.match(archiveContents, /desktop-annotated\.png/);
    assert.match(archiveContents, /mobile-annotated\.png/);
    const annotatedImage = execFileSync('/usr/bin/unzip', ['-p', handoffPath, '*/page-1-desktop-annotated.png']);
    assert.ok(annotatedImage.length > 10000, 'The annotated image does not contain meaningful page context.');
    const handoffJson = execFileSync('/usr/bin/unzip', ['-p', handoffPath, '*/handoff.json'], { encoding: 'utf8' });
    assert.match(handoffJson, /Move the marked block closer to the heading/);
    assert.match(handoffJson, /"breakpoint": "desktop"/);
    assert.match(handoffJson, /"pages": \[/);
    assert.match(handoffJson, /"strokes": \[/);
    assert.match(handoffJson, /"tool": "arrow"/);
    const startHere = execFileSync('/usr/bin/unzip', ['-p', handoffPath, '*/START-HERE.md'], { encoding: 'utf8' });
    assert.match(startHere, /Do not blindly paste selectors/);
    assert.equal(await evaluate(`document.querySelector('#handoffName').textContent.endsWith('.zip')`), true);
    await evaluate(`document.querySelector('#copyHandoffPath').click()`);
    await poll(() => evaluate(`document.querySelector('#status').textContent.includes('path copied')`));
    process.stdout.write('AI handoff archive and path controls passed.\n');

    await evaluate(`(() => { const address = document.querySelector('#address'); address.value = 'example.com'; address.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').getURL().startsWith('https://example.com')`));
    const fileUrl = pathToFileURL(fixture).href;
    await evaluate(`(() => { const transfer = new DataTransfer(); transfer.setData('text/uri-list', ${JSON.stringify(fileUrl)}); document.body.dispatchEvent(new DragEvent('drop', { dataTransfer: transfer, bubbles: true, cancelable: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').getURL() === ${JSON.stringify(fileUrl)}`));
    const protocolTarget = 'https://example.com/?from=bookmarklet';
    const launcher = launch([`--user-data-dir=${profile}`, `page-tweaker://open?url=${encodeURIComponent(protocolTarget)}`]);
    await poll(() => evaluate(`document.querySelector('#page').getURL() === ${JSON.stringify(protocolTarget)}`));
    launcher.kill('SIGTERM');

    await evaluate(`(() => { const address = document.querySelector('#address'); address.value = ${JSON.stringify(fileUrl)}; address.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); })()`);
    await poll(() => evaluate(`document.querySelector('#page').getURL() === ${JSON.stringify(fileUrl)}`));
    await evaluate(`document.querySelector('#page').executeJavaScript("localStorage.setItem('pageTweakerPersistentSmoke', 'retained')")`);
    client.socket.close();
    app.kill('SIGTERM');
    await new Promise((resolve) => app.once('exit', resolve));
    app = launch([`--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, fixture]);
    client = await connect();
    await poll(() => client.evaluate(`document.querySelector('#status').textContent.includes('Click an element')`));
    assert.equal(await client.evaluate(`document.querySelector('#page').executeJavaScript("localStorage.getItem('pageTweakerPersistentSmoke')")`), 'retained');
    await client.evaluate(`window.confirm = () => true; document.querySelector('#clearPage').click()`);
    await poll(() => client.evaluate(`document.querySelector('#empty').hidden === false && document.querySelector('#address').value === ''`));
    assert.equal(await client.evaluate(`document.querySelector('#page').getURL()`), 'about:blank');
    const imageUrl = pathToFileURL(imageFixture).href;
    await client.evaluate(`(() => { const transfer = new DataTransfer(); transfer.setData('text/uri-list', ${JSON.stringify(imageUrl)}); document.body.dispatchEvent(new DragEvent('drop', { dataTransfer: transfer, bubbles: true, cancelable: true })); })()`);
    await poll(() => client.evaluate(`document.querySelector('#page').getURL() === ${JSON.stringify(imageUrl)}`));
    assert.equal(await client.evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('img')?.naturalWidth > 0")`), true);
    await poll(() => client.evaluate(`document.querySelector('#iterationDisplay').style.width !== ''`));
    assert.equal(await client.evaluate(`document.querySelector('#iterationDisplay').getBoundingClientRect().width > document.querySelector('#iterationDisplay').naturalWidth`), true);
    assert.equal(await client.evaluate(`document.querySelector('#imageNotes').hidden`), false);
    assert.equal(await client.evaluate(`document.querySelector('#controls').hidden`), true);
    assert.equal(await client.evaluate(`document.querySelector('.interaction-tip').hidden`), true);
    assert.equal(await client.evaluate(`document.querySelector('#markup').style.cursor`), 'default');
    await client.evaluate(`(() => { const note = document.querySelector('#imageNote'); note.value = 'Use this image as the overall visual direction.'; document.querySelector('#addImageNote').click(); })()`);
    assert.match(await client.evaluate(`document.querySelector('#notes').textContent`), /overall visual direction/i);
    await client.evaluate(`document.querySelector('#markupTab').click()`);
    assert.equal(await client.evaluate(`document.querySelector('#markup').style.cursor`), 'crosshair');
    await client.evaluate(`document.querySelector('#inspectTab').click()`);
    execFileSync('/usr/bin/osascript', ['-e', `set the clipboard to (read (POSIX file ${JSON.stringify(imageFixture)}) as «class PNGf»)`]);
    const clipboardImageUrl = await client.evaluate(`window.pageTweaker.clipboardImage()`);
    assert.match(clipboardImageUrl, /^file:\/\/.*page-tweaker-clipboard-\d+\.png$/);
    await client.evaluate(`(() => { const address = document.querySelector('#address'); address.value = ${JSON.stringify(clipboardImageUrl)}; address.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); })()`);
    await poll(() => client.evaluate(`document.querySelector('#page').getURL() === ${JSON.stringify(clipboardImageUrl)}`));
    assert.equal(await client.evaluate(`document.querySelector('#page').executeJavaScript("document.querySelector('img')?.naturalWidth > 0")`), true);
    process.stdout.write('Image file drop and clipboard screenshot loading passed.\n');
    await client.evaluate(`(() => { document.querySelector('#markupTab').click(); const note = document.querySelector('#markupExplanation'); note.value = 'Keep the small icon visible.'; note.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    const markupStart = await client.evaluate(`(() => { const stage = document.querySelector('#stage').getBoundingClientRect(); return { x: stage.left + 80, y: stage.top + 80 }; })()`);
    await client.command('Input.dispatchMouseEvent', { type: 'mouseMoved', ...markupStart });
    await client.command('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'left', clickCount: 1, ...markupStart });
    await client.command('Input.dispatchMouseEvent', { type: 'mouseMoved', button: 'left', buttons: 1, x: markupStart.x + 50, y: markupStart.y + 50 });
    await client.command('Input.dispatchMouseEvent', { type: 'mouseReleased', button: 'left', clickCount: 1, x: markupStart.x + 50, y: markupStart.y + 50 });
    await poll(() => client.evaluate(`state.strokes.length > 0`));
    await poll(() => client.evaluate(`document.querySelector('#iterationDisplay').naturalWidth > 0`));
    assert.equal(await client.evaluate(`getComputedStyle(document.querySelector('#protectLabelRow')).display`), 'none');
    await client.evaluate(`(() => { document.querySelector('#imageTab').click(); const text = document.querySelector('#editInstruction'); text.value = 'Change the center to red.'; text.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    const regionBox = await client.evaluate(`(() => { const box = document.querySelector('#regionCanvas').getBoundingClientRect(); return { left: box.left, top: box.top, width: box.width, height: box.height }; })()`);
    const drawRegion = async (x1, y1, x2, y2) => {
      const first = { x: regionBox.left + regionBox.width * x1, y: regionBox.top + regionBox.height * y1 };
      const last = { x: regionBox.left + regionBox.width * x2, y: regionBox.top + regionBox.height * y2 };
      await client.command('Input.dispatchMouseEvent', { type: 'mouseMoved', ...first });
      await client.command('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'left', clickCount: 1, ...first });
      await client.command('Input.dispatchMouseEvent', { type: 'mouseMoved', button: 'left', buttons: 1, ...last });
      await client.command('Input.dispatchMouseEvent', { type: 'mouseReleased', button: 'left', clickCount: 1, ...last });
    };
    await drawRegion(.2, .2, .8, .8);
    await client.evaluate(`(() => { const kind = document.querySelector('#regionKind'); kind.value = 'protect'; kind.dispatchEvent(new Event('change', { bubbles: true })); document.querySelector('#protectLabel').value = 'Logo'; })()`);
    await drawRegion(.4, .4, .5, .5);
    assert.match(await client.evaluate(`document.querySelector('#regionList').textContent`), /Keep exactly: Logo/);
    await client.evaluate(`document.querySelector('#export').click()`);
    try { await poll(() => client.evaluate(`!document.querySelector('#handoffReady').hidden`)); }
    catch (error) { throw new Error(`Image handoff did not finish: ${await client.evaluate(`document.querySelector('#status').textContent`)}`, { cause: error }); }
    const imageHandoff = await client.evaluate(`document.querySelector('#handoffPath').value`);
    const imageArchive = execFileSync('/usr/bin/unzip', ['-Z1', imageHandoff], { encoding: 'utf8' });
    assert.match(imageArchive, /original\.png/); assert.match(imageArchive, /edit-mask\.png/); assert.match(imageArchive, /marked-preview\.png/);
    assert.match(imageArchive, /page-1-desktop-annotated\.png/);
    const maskPath = path.join(profile, 'edit-mask.png');
    fs.writeFileSync(maskPath, execFileSync('/usr/bin/unzip', ['-p', imageHandoff, '*/edit-mask.png']));
    const maskPixels = await client.evaluate(`(async () => { const image = new Image(); image.src = await window.pageTweaker.readImage(${JSON.stringify(maskPath)}); await image.decode(); const canvas = document.createElement('canvas'); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; const context = canvas.getContext('2d'); context.drawImage(image, 0, 0); const alpha = (x, y) => context.getImageData(Math.floor(x * canvas.width), Math.floor(y * canvas.height), 1, 1).data[3]; return { outside: alpha(.1, .1), change: alpha(.3, .3), protected: alpha(.45, .45) }; })()`);
    assert.deepEqual(maskPixels, { outside: 255, change: 0, protected: 255 });
    const imagePrompt = execFileSync('/usr/bin/unzip', ['-p', imageHandoff, '*/START-HERE.md'], { encoding: 'utf8' });
    assert.match(imagePrompt, /Change the center to red/); assert.match(imagePrompt, /Logo/); assert.match(imagePrompt, /PageTweaker will merge/);
    const imageJson = execFileSync('/usr/bin/unzip', ['-p', imageHandoff, '*/handoff.json'], { encoding: 'utf8' });
    assert.match(imageJson, /Keep the small icon visible/);
    await client.evaluate(`document.querySelector('#imageTab').click()`);
    const candidateData = await client.evaluate(`(() => { const image = document.querySelector('#iterationDisplay'); const canvas = document.createElement('canvas'); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; const context = canvas.getContext('2d'); context.fillStyle = '#ff0000'; context.fillRect(0, 0, canvas.width, canvas.height); return canvas.toDataURL('image/png'); })()`);
    const candidatePath = path.join(profile, 'returned-image.png');
    fs.writeFileSync(candidatePath, Buffer.from(candidateData.split(',')[1], 'base64'));
    await client.evaluate(`imageWorkspace.loadCandidate(${JSON.stringify(candidatePath)})`);
    await poll(() => client.evaluate(`!document.querySelector('#saveResult').disabled`));
    const pixelResult = await client.evaluate(`(async () => { const original = new Image(); original.src = await window.pageTweaker.readImage(${JSON.stringify(clipboardImageUrl)}); await original.decode(); const merged = document.querySelector('#iterationDisplay'); await merged.decode(); const sample = (image, x, y) => { const canvas = document.createElement('canvas'); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; const context = canvas.getContext('2d'); context.drawImage(image, 0, 0); return [...context.getImageData(Math.floor(x * canvas.width), Math.floor(y * canvas.height), 1, 1).data]; }; return { outside: [sample(original, .1, .1), sample(merged, .1, .1)], protected: [sample(original, .45, .45), sample(merged, .45, .45)], changed: sample(merged, .3, .3) }; })()`);
    assert.deepEqual(pixelResult.outside[1], pixelResult.outside[0]);
    assert.deepEqual(pixelResult.protected[1], pixelResult.protected[0]);
    assert.deepEqual(pixelResult.changed, [255, 0, 0, 255]);
    await client.evaluate(`document.querySelector('#saveResult').click()`);
    await poll(() => client.evaluate(`document.querySelector('#candidateStatus').textContent.includes('Merged PNG saved:')`));
    const savedImage = (await client.evaluate(`document.querySelector('#candidateStatus').textContent`)).replace('Merged PNG saved: ', '');
    assert.equal(fs.existsSync(savedImage), true);
    process.stdout.write('Image iteration handoff, protected-pixel merge, and saved PNG passed.\n');
    process.stdout.write('Packaged UI smoke passed: safe formatted content, clear-page flow, image input, interactive-control pass-through, Option-click selection, bookmarklet copy and protocol launch, persistent preview storage across relaunch, breakpoint isolation, loading, editing, markup, and AI handoff.\n');
  } finally {
    client?.socket.close();
    app.kill('SIGTERM');
    await delay(500);
    fs.rmSync(profile, { recursive: true, force: true });
  }
})().catch((error) => { console.error(error); process.exitCode = 1; });
