const page = document.querySelector('#page');
const address = document.querySelector('#address');
const back = document.querySelector('#back');
const status = document.querySelector('#status');
const controls = document.querySelector('#controls');
const selection = document.querySelector('#selection');
const interactionTip = document.querySelector('.interaction-tip');
const imageNotes = document.querySelector('#imageNotes');
const canvas = document.querySelector('#markup');
const ctx = canvas.getContext('2d');
const stage = document.querySelector('#stage');
const dropHint = document.querySelector('#dropHint');
const aside = document.querySelector('aside');
const utils = window.PageTweakerUtils;
const desktopBridge = window.pageTweaker;
const breakpoints = { desktop: { label: 'Desktop', width: 1440 }, tablet: { label: 'Tablet', width: 834 }, mobile: { label: 'Mobile', width: 390 } };
const state = { source: '', pageOrder: [], breakpoint: 'desktop', visitedBreakpoints: new Set(['desktop']), annotatedImages: {}, pageScroll: { x: 0, y: 0 }, selected: null, scope: null, scopeDefinitions: new Map(), cssTweaks: new Map(), textChanges: new Map(), originalStyles: new Map(), originalTexts: new Map(), notes: [], strokes: [], markupExplanation: '', currentMarkupGroupId: null, handoffPath: '', activeTab: 'inspect', annotating: false, annotationColor: '#f25f5c', annotationWidth: 3, annotationTool: 'freehand' };
const pendingEdits = new Map();
const pendingSessions = new Map();
let textPreviewTimer = null;
let navigationTrail = [];
let navigationIndex = -1;

function setStatus(message) { status.textContent = message; }
function updateNavigationControls() { back.disabled = !state.source || navigationIndex <= 0; }
function hasSessionWork() { return state.cssTweaks.size || state.textChanges.size || state.notes.length || state.strokes.length || state.markupExplanation.trim(); }
function makePrompt(handoff) { const sections = handoff.pages.map((pageRecord, pageIndex) => { const sizes = Object.keys(breakpoints).map((breakpoint) => { const styles = pageRecord.previewStyleEvidence.filter((item) => item.breakpoint === breakpoint).map((item) => `- Visual target near \`${item.selector}\`: ${Object.entries(item.previewValues).map(([name, value]) => `${name} ${value}`).join(', ')}.`); const texts = pageRecord.previewTextEvidence.filter((item) => item.breakpoint === breakpoint).map((item) => `- Desired text near \`${item.selector}\`: “${item.previewText}”`); const notes = pageRecord.feedbackNotes.filter((item) => item.breakpoint === breakpoint).map((item) => `- Feedback near \`${item.selector}\`: ${item.note}`); const marks = pageRecord.markup.filter((item) => item.breakpoint === breakpoint).map((item) => `- Drawn feedback near \`${item.strokes[0]?.anchor?.selector || 'the recorded page coordinates'}\`: ${item.explanation || 'No explanation was entered.'} (${item.strokes.length} stroke${item.strokes.length === 1 ? '' : 's'} in this markup item.)`); const items = [...styles, ...texts, ...notes, ...marks]; return items.length ? `### ${breakpoints[breakpoint].label} feedback (${breakpoints[breakpoint].width}px preview)\n\n${items.join('\n')}` : ''; }).filter(Boolean).join('\n\n'); return sizes ? `## Page ${pageIndex + 1}: ${pageRecord.url}\n\n${sizes}` : ''; }).filter(Boolean).join('\n\n'); return `# AI PagePolish by PageTweaker feedback brief for an AI agent\n\nThe user used AI PagePolish by PageTweaker to try changes visually before asking you to modify the real project. This archive separates feedback by page URL and preview size so changes from different pages are never mixed.\n\n## Important implementation rule\n\nTreat selectors, element names, current values, preview values, coordinates, and replacement text as evidence describing the user's desired outcome. They identify what the user was looking at; they do not prescribe the final code structure. Inspect the actual project and choose the implementation that fits its existing components, CSS system, responsive rules, accessibility requirements, and conventions. Do not blindly paste selectors, create elements merely because a selector names one, or treat preview values as a request to replace the project's responsive architecture. Preserve unrelated work.\n\n${sections || 'No feedback items were recorded.'}\n\n## Files\n\nRead \`handoff.json\` for complete page, breakpoint, and grouped-markup evidence. Annotated PNG files are named by page and preview size. Each markup item may contain several strokes that share one explanation. First infer the desired outcome, then implement it appropriately in the real system and verify the result at every referenced page and breakpoint.`; }
function scopedKey(key) { return JSON.stringify([state.source, state.breakpoint, key]); }
function parseScopedKey(key) { try { return JSON.parse(key); } catch { return ['', '', key]; } }
function currentBreakpointItems(items) { return items.filter((item) => item.pageUrl === state.source && item.breakpoint === state.breakpoint); }
function imageMode() { return utils.isImageSource(state.source); }
function resizeCanvas() { const box = page.getBoundingClientRect(); canvas.width = box.width * devicePixelRatio; canvas.height = box.height * devicePixelRatio; canvas.style.width = `${box.width}px`; canvas.style.height = `${box.height}px`; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); drawMarkup(); }
function drawStroke(mark) { const points = mark.points || []; if (!points.length) return; const start = points[0]; const end = points[points.length - 1]; const x1 = start.x - state.pageScroll.x; const y1 = start.y - state.pageScroll.y; const x2 = end.x - state.pageScroll.x; const y2 = end.y - state.pageScroll.y; ctx.strokeStyle = mark.color; ctx.lineWidth = mark.width; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); if (mark.tool === 'rectangle') ctx.rect(Math.min(x1, x2), Math.min(y1, y2), Math.abs(x2 - x1), Math.abs(y2 - y1)); else if (mark.tool === 'circle') ctx.ellipse((x1 + x2) / 2, (y1 + y2) / 2, Math.abs(x2 - x1) / 2, Math.abs(y2 - y1) / 2, 0, 0, Math.PI * 2); else { points.forEach((point, index) => { const x = point.x - state.pageScroll.x; const y = point.y - state.pageScroll.y; index ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); } ctx.stroke(); if (mark.tool === 'arrow' && points.length > 1) { const angle = Math.atan2(y2 - y1, x2 - x1); const size = Math.max(10, mark.width * 3); ctx.beginPath(); ctx.moveTo(x2, y2); ctx.lineTo(x2 - size * Math.cos(angle - Math.PI / 6), y2 - size * Math.sin(angle - Math.PI / 6)); ctx.moveTo(x2, y2); ctx.lineTo(x2 - size * Math.cos(angle + Math.PI / 6), y2 - size * Math.sin(angle + Math.PI / 6)); ctx.stroke(); } }
function drawMarkup() { const box = page.getBoundingClientRect(); ctx.clearRect(0, 0, box.width, box.height); const visibleStrokes = currentBreakpointItems(state.strokes); visibleStrokes.forEach(drawStroke); if (stroke) drawStroke(stroke); const groups = []; visibleStrokes.forEach((item) => { if (!groups.some((group) => group.groupId === item.groupId)) groups.push(item); }); groups.forEach((item, index) => { const point = item.points[0]; if (!point) return; const label = item.explanation.trim() ? `${index + 1}. ${item.explanation.trim().replace(/\s+/g, ' ').slice(0, 52)}${item.explanation.trim().length > 52 ? '…' : ''}` : `Markup ${index + 1}`; const x = Math.max(8, point.x - state.pageScroll.x); const y = Math.max(8, point.y - state.pageScroll.y - 31); ctx.font = '12px sans-serif'; const width = Math.min(box.width - x - 8, ctx.measureText(label).width + 30); if (width <= 20) return; ctx.fillStyle = 'rgba(17,19,24,.9)'; ctx.beginPath(); ctx.roundRect(x, y, width, 25, 6); ctx.fill(); ctx.fillStyle = item.color; ctx.beginPath(); ctx.arc(x + 11, y + 12.5, 4, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#eef2f7'; ctx.fillText(label, x + 21, y + 17, width - 26); }); currentBreakpointItems(state.notes).forEach((note, index) => { const x = note.documentBox.x - state.pageScroll.x; const y = note.documentBox.y - state.pageScroll.y; if (x < -25 || y < -25 || x > box.width || y > box.height) return; ctx.fillStyle = '#ffca56'; ctx.beginPath(); ctx.arc(x + 10, y + 10, 10, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#161616'; ctx.font = '11px sans-serif'; ctx.fillText(String(index + 1), x + 7, y + 14); }); }
function renderNotes() { const list = document.querySelector('#notes'); list.replaceChildren(); currentBreakpointItems(state.notes).forEach((note, index) => { const item = document.createElement('div'); item.className = 'note'; const title = document.createElement('strong'); title.textContent = `${index + 1}. ${breakpoints[note.breakpoint].label}: pinned to ${note.tag}`; item.append(title, document.createElement('br'), document.createTextNode(note.text || note.selector), document.createElement('br'), document.createTextNode(note.note)); list.append(item); }); }
function renderStrokes() { const list = document.querySelector('#strokeList'); list.replaceChildren(); const groups = []; currentBreakpointItems(state.strokes).forEach((stroke) => { let group = groups.find((item) => item.id === stroke.groupId); if (!group) { group = { id: stroke.groupId, strokes: [] }; groups.push(group); } group.strokes.push(stroke); }); if (!groups.length) { const empty = document.createElement('p'); empty.className = 'hint'; empty.textContent = `No ${breakpoints[state.breakpoint].label.toLowerCase()} markup items yet.`; list.append(empty); return; } groups.forEach((group, visibleIndex) => { const item = document.createElement('div'); item.className = 'stroke-item stroke-detail'; const heading = document.createElement('span'); const color = document.createElement('i'); color.style.background = group.strokes[0].color; heading.append(color, document.createTextNode(` Markup ${visibleIndex + 1} · ${group.strokes.length} stroke${group.strokes.length === 1 ? '' : 's'}`)); const remove = document.createElement('button'); remove.textContent = 'Remove'; remove.title = 'Remove this markup item'; remove.addEventListener('click', () => { state.strokes = state.strokes.filter((stroke) => stroke.groupId !== group.id); if (state.currentMarkupGroupId === group.id) finishCurrentMarkup({ silent: true }); renderStrokes(); drawMarkup(); setStatus('Markup item removed.'); }); const explanation = document.createElement('textarea'); explanation.value = group.strokes[0].explanation; explanation.placeholder = 'Explain what this markup item means'; explanation.addEventListener('input', () => { group.strokes.forEach((stroke) => { stroke.explanation = explanation.value; }); if (state.currentMarkupGroupId === group.id) { state.markupExplanation = explanation.value; document.querySelector('#markupExplanation').value = explanation.value; } }); item.append(heading, remove, explanation); list.append(item); }); }
document.querySelector('#strokeList').addEventListener('input', drawMarkup);
document.querySelector('#markupExplanation').addEventListener('input', drawMarkup);
function pageImageKey(url, breakpoint = state.breakpoint) { return `page-${Math.max(0, state.pageOrder.indexOf(url)) + 1}-${breakpoint}`; }
function clearPageSession(url) { state.scopeDefinitions = new Map([...state.scopeDefinitions].filter(([key]) => parseScopedKey(key)[0] !== url)); state.cssTweaks = new Map([...state.cssTweaks].filter(([key]) => parseScopedKey(key)[0] !== url)); state.textChanges = new Map([...state.textChanges].filter(([key]) => parseScopedKey(key)[0] !== url)); state.originalStyles = new Map([...state.originalStyles].filter(([key]) => parseScopedKey(key)[0] !== url)); state.originalTexts = new Map([...state.originalTexts].filter(([key]) => parseScopedKey(key)[0] !== url)); state.notes = state.notes.filter((item) => item.pageUrl !== url); state.strokes = state.strokes.filter((item) => item.pageUrl !== url); const imagePrefix = `page-${state.pageOrder.indexOf(url) + 1}-`; Object.keys(state.annotatedImages).filter((key) => key.startsWith(imagePrefix)).forEach((key) => delete state.annotatedImages[key]); }
function configureInspectorForSource() { const image = imageMode(); interactionTip.hidden = image; imageNotes.hidden = !image; selection.hidden = image; controls.hidden = true; document.querySelector('#selectorBar').hidden = true; if (!image) { selection.hidden = false; selection.innerHTML = '<h2>Select an element</h2><p>Click anything in the preview to adjust it.</p>'; } }
function resetWorkspaceUi() { state.breakpoint = 'desktop'; state.visitedBreakpoints = new Set(['desktop']); state.pageScroll = { x: 0, y: 0 }; state.selected = null; state.scope = null; state.markupExplanation = ''; state.currentMarkupGroupId = null; stage.style.setProperty('--preview-width', `${breakpoints.desktop.width}px`); document.querySelectorAll('[data-breakpoint]').forEach((button) => button.classList.toggle('active', button.dataset.breakpoint === 'desktop')); interactionTip.hidden = false; imageNotes.hidden = true; selection.hidden = false; controls.hidden = true; selection.innerHTML = '<h2>Select an element</h2><p>Click anything in the preview to adjust it.</p>'; document.querySelector('#selectorBar').hidden = true; document.querySelector('#notes').innerHTML = ''; document.querySelector('#text').value = ''; document.querySelector('#note').value = ''; document.querySelector('#imageNote').value = ''; document.querySelector('#markupExplanation').value = ''; document.querySelector('#markupSaved').textContent = 'Draw one or more strokes for this markup item.'; setTab('inspect', { silent: true }); renderStrokes(); drawMarkup(); }
function clearSession() { state.pageOrder = []; state.annotatedImages = {}; state.scopeDefinitions.clear(); state.cssTweaks.clear(); state.textChanges.clear(); state.originalStyles.clear(); state.originalTexts.clear(); state.notes = []; state.strokes = []; state.handoffPath = ''; document.querySelector('#handoffEmpty').hidden = false; document.querySelector('#handoffReady').hidden = true; resetWorkspaceUi(); }
function setTab(tab, { silent = false } = {}) { const panels = { inspect: 'inspectPanel', markup: 'annotationControls', help: 'helpPanel', handoff: 'handoffPanel' }; const tabs = { inspect: 'inspectTab', markup: 'markupTab', help: 'helpPanel', handoff: 'handoffPanel' }; state.activeTab = tab; state.annotating = tab === 'markup'; canvas.style.pointerEvents = state.annotating ? 'auto' : 'none'; canvas.style.cursor = state.annotating ? 'crosshair' : 'default'; if (state.source) page.send('set-inspector', tab === 'inspect' && !imageMode()); Object.entries(panels).forEach(([name, id]) => { document.querySelector(`#${id}`).hidden = name !== tab; }); const tabIds = { inspect: 'inspectTab', markup: 'markupTab', help: 'helpTab', handoff: 'handoffTab' }; Object.entries(tabIds).forEach(([name, id]) => { const button = document.querySelector(`#${id}`); const active = name === tab; button.classList.toggle('active', active); button.setAttribute('aria-selected', String(active)); button.tabIndex = active ? 0 : -1; }); aside.scrollTop = 0; if (!silent) setStatus(tab === 'markup' ? `Markup mode at ${breakpoints[state.breakpoint].label}: explain the next mark, then draw it.` : tab === 'help' ? 'Learn how to preview feedback and give the resulting brief to an AI session.' : tab === 'handoff' ? 'Create or share the complete feedback file with your AI session.' : imageMode() ? `Image notes at ${breakpoints[state.breakpoint].label}: add overall guidance or choose Markup to point at a specific area.` : `Inspect mode at ${breakpoints[state.breakpoint].label}: click an element to adjust it.`); }
function showFreshPageUi() { state.pageScroll = { x: 0, y: 0 }; state.selected = null; state.scope = null; state.currentMarkupGroupId = null; state.markupExplanation = ''; configureInspectorForSource(); if (!imageMode()) selection.innerHTML = `<h2>${breakpoints[state.breakpoint].label} preview</h2><p>Click an element to adjust it on this page.</p>`; document.querySelector('#markupExplanation').value = ''; document.querySelector('#markupSaved').textContent = 'Draw one or more strokes for this markup item.'; renderNotes(); renderStrokes(); drawMarkup(); updateNavigationControls(); }
function activateNavigatedPage(url) { const source = utils.normalizeSource(url); if (!source || source === state.source) return false; if (navigationIndex > 0 && navigationTrail[navigationIndex - 1] === source) navigationIndex -= 1; else { navigationTrail = navigationTrail.slice(0, navigationIndex + 1); navigationTrail.push(source); navigationIndex += 1; } state.source = source; if (!state.pageOrder.includes(source)) state.pageOrder.push(source); address.value = source; showFreshPageUi(); return true; }
function open(rawValue, { reload = false } = {}) { if (!desktopBridge) return setStatus('Launch AI PagePolish by PageTweaker.app. Opening src/index.html directly in a browser cannot inspect elements or export bundles.'); const source = reload ? state.source : utils.normalizeSource(rawValue); if (!source) return setStatus('Paste a screenshot, file:// URL, public website URL, or path to an HTML or image file.'); const sameSource = source === state.source; const replacing = Boolean(state.source) && (reload || !sameSource || hasSessionWork()); if (replacing && !window.confirm(`Load ${reload ? 'this page again' : 'the new starting page'}? This clears ${reload ? 'this page’s' : 'the current session’s'} preview edits, pins, and markup.`)) { address.value = state.source; return; } if (reload) { clearPageSession(state.source); resetWorkspaceUi(); } else { clearSession(); state.source = source; state.pageOrder = [source]; navigationTrail = [source]; navigationIndex = 0; } address.value = source; document.querySelector('#empty').hidden = true; updateNavigationControls(); if (reload || sameSource) page.reloadIgnoringCache(); else page.src = source; setStatus(reload || sameSource ? 'Reloading a clean preview…' : 'Loading a fresh preview…'); }
function currentChanges() { return state.scope ? state.cssTweaks.get(scopedKey(state.scope.key)) || {} : {}; }
function executeSelected(action, payload, { exact = false } = {}) { const id = `edit-${Date.now()}-${Math.random().toString(16).slice(2)}`; const scope = exact ? state.selected.scopes[0] : state.scope; return new Promise((resolve, reject) => { const timeout = setTimeout(() => { pendingEdits.delete(id); reject(new Error('The page did not acknowledge the change. Select the element again.')); }, 1500); pendingEdits.set(id, { resolve, reject, timeout }); page.send('apply-edit', { id, action, targetId: state.selected.targetId, scope, ...payload }); }); }
function colorToHex(rawValue) { const match = rawValue.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/); return match ? `#${[match[1], match[2], match[3]].map((value) => Number(value).toString(16).padStart(2, '0')).join('')}` : /^#[0-9a-f]{6}$/i.test(rawValue) ? rawValue.toLowerCase() : '#000000'; }
function normalizeHex(rawValue) { const value = rawValue.trim().toLowerCase(); if (/^#[0-9a-f]{6}$/.test(value)) return value; if (/^#[0-9a-f]{3}$/.test(value)) return `#${[...value.slice(1)].map((character) => character.repeat(2)).join('')}`; return null; }
function syncHexControl(property, value) { const hex = document.querySelector(`[data-hex-for="${property}"]`); if (hex) hex.value = value; }
function markControlModified(property, modified) { const button = document.querySelector(`[data-reset-style="${property}"]`); if (!button) return; button.classList.toggle('modified', modified); button.setAttribute('aria-pressed', String(modified)); }
function setControlValues(style) { const changes = currentChanges(); document.querySelectorAll('[data-style]').forEach((control) => { const property = control.dataset.style; const rawValue = utils.readableValue(style, property) || ''; markControlModified(property, Object.hasOwn(changes, property)); if (control.tagName === 'SELECT') { control.value = changes[property] || ''; return; } if (control.type === 'color') { control.value = colorToHex(rawValue); syncHexControl(property, control.value); return; } const bounds = utils.sliderBounds(property, rawValue); control.min = bounds.min; control.max = bounds.max; control.step = bounds.step; control.value = bounds.value; const output = control.closest('.control-group')?.querySelector('output'); if (output) output.value = bounds.value; }); }
function setOneControl(property, style) { const control = document.querySelector(`[data-style="${property}"]`); if (!control) return; const rawValue = utils.readableValue(style, property) || ''; markControlModified(property, false); if (control.tagName === 'SELECT') control.value = ''; else if (control.type === 'color') { control.value = colorToHex(rawValue); syncHexControl(property, control.value); } else { const bounds = utils.sliderBounds(property, rawValue); control.min = bounds.min; control.max = bounds.max; control.step = bounds.step; control.value = bounds.value; const output = control.closest('.control-group')?.querySelector('output'); if (output) output.value = bounds.value; } }
function setScope(scope) { state.scope = scope; state.scopeDefinitions.set(scopedKey(scope.key), scope); document.querySelectorAll('[data-scope-key]').forEach((button) => button.classList.toggle('active', button.dataset.scopeKey === scope.key)); document.querySelector('#scopeSummary').textContent = scope.kind === 'exact' ? `Changes affect only this element at ${breakpoints[state.breakpoint].label}.` : `Changes affect ${scope.count} matching elements at ${breakpoints[state.breakpoint].label}.`; setControlValues({ ...state.selected.style, ...currentChanges() }); setStatus(scope.kind === 'exact' ? `Editing this element only at ${breakpoints[state.breakpoint].label}.` : `Editing all ${scope.count} elements matching ${scope.selector} at ${breakpoints[state.breakpoint].label}.`); }
function showSelection(selected) { selection.replaceChildren(); const heading = document.createElement('h2'); heading.textContent = `Selected: ${selected.tag}`; const excerpt = document.createElement('p'); excerpt.textContent = selected.text || 'No readable text'; selection.append(heading, excerpt); document.querySelector('#pinContext').textContent = `This note will stay attached to this ${selected.tag} while the page scrolls.`; const bar = document.querySelector('#selectorBar'); bar.hidden = false; const choices = document.querySelector('#scopeChoices'); choices.replaceChildren(); selected.scopes.forEach((scope) => { const button = document.createElement('button'); button.dataset.scopeKey = scope.key; button.title = scope.selector; button.textContent = `${scope.label}${scope.kind === 'all' ? ` (${scope.count})` : ''}`; button.addEventListener('click', () => setScope(scope)); choices.append(button); }); document.querySelector('#selectorPath').textContent = selected.selector; setScope(selected.scopes[0]); }
function setAnnotationColor(color) { const startsNewItem = Boolean(state.currentMarkupGroupId && color !== state.annotationColor); if (startsNewItem) finishCurrentMarkup({ silent: true }); state.annotationColor = color; document.querySelectorAll('[data-color]').forEach((button) => button.classList.toggle('active', button.dataset.color === color)); if (startsNewItem) setStatus('Color changed. The previous markup item was saved; your next stroke starts a new one.'); }

function applyCurrentBreakpoint({ reset = false } = {}) { const styles = [...state.cssTweaks].filter(([key]) => { const [url, breakpoint] = parseScopedKey(key); return url === state.source && breakpoint === state.breakpoint; }).map(([key, changes]) => { const [, , rawKey] = parseScopedKey(key); return { selector: state.scopeDefinitions.get(key)?.selector || rawKey.replace(/^exact:/, ''), changes }; }); const texts = [...state.textChanges].filter(([key]) => { const [url, breakpoint] = parseScopedKey(key); return url === state.source && breakpoint === state.breakpoint; }).map(([key, text]) => ({ selector: parseScopedKey(key)[2], text })); const id = `session-${Date.now()}-${Math.random().toString(16).slice(2)}`; return new Promise((resolve, reject) => { const timeout = setTimeout(() => { pendingSessions.delete(id); reject(new Error('The preview did not finish restoring this breakpoint.')); }, 2000); pendingSessions.set(id, { resolve, reject, timeout }); page.send('apply-session', { id, reset, styles, texts }); }); }
function trackNavigation(event) { if (event.isMainFrame === false) return; activateNavigatedPage(event.url); }
page.addEventListener('will-navigate', () => { finishCurrentMarkup({ silent: true }); captureCurrentVisual().catch(() => {}); });
page.addEventListener('did-navigate', trackNavigation);
page.addEventListener('did-navigate-in-page', (event) => { if (event.isMainFrame === false || !activateNavigatedPage(event.url)) return; setTimeout(() => applyCurrentBreakpoint({ reset: true }).catch(() => {}), 0); });
page.addEventListener('did-finish-load', () => { if (!state.source && page.getURL() === 'about:blank') return updateNavigationControls(); activateNavigatedPage(page.getURL()); state.pageScroll = { x: 0, y: 0 }; configureInspectorForSource(); page.send('set-inspector', state.activeTab === 'inspect' && !imageMode()); if (imageMode()) page.executeJavaScript("document.documentElement.style.cursor='default'; document.body.style.cursor='default'; document.querySelector('img')?.style.setProperty('cursor','default','important'); true").catch(() => {}); applyCurrentBreakpoint().catch(() => {}); resizeCanvas(); renderNotes(); renderStrokes(); updateNavigationControls(); setStatus(imageMode() ? 'Image loaded. Add an overall AI note or choose Markup to point at a specific area.' : state.activeTab === 'inspect' ? `Click an element to inspect and tweak page ${state.pageOrder.indexOf(state.source) + 1} at ${breakpoints[state.breakpoint].label}.` : 'Page loaded. Choose Inspect to select an element.'); });
page.addEventListener('ipc-message', (_event) => { const [message] = _event.args; if (_event.channel === 'interactive-guidance') { setStatus(`Use this ${message?.tag || 'control'} normally. Hold Option (⌥) while clicking it to select it for AI PagePolish by PageTweaker.`); return; } if (_event.channel === 'edit-result') { const pending = pendingEdits.get(message.id); if (!pending) return; clearTimeout(pending.timeout); pendingEdits.delete(message.id); message.ok ? pending.resolve(message) : pending.reject(new Error(message.message)); return; } if (_event.channel === 'session-applied') { const pending = pendingSessions.get(message.id); if (!pending) return; clearTimeout(pending.timeout); pendingSessions.delete(message.id); message.ok ? pending.resolve(message) : pending.reject(new Error(message.message)); return; } if (_event.channel === 'page-scroll') { state.pageScroll = message; drawMarkup(); return; } if (_event.channel === 'point-context') { const targetStroke = stroke?.contextId === message.id ? stroke : state.strokes.find((item) => item.contextId === message.id); if (targetStroke) targetStroke.anchor = { selector: message.selector, tag: message.tag, text: message.text }; return; } if (_event.channel === 'element-position') { if (state.selected?.targetId === message.targetId) state.selected.box = message.box; state.notes.filter((note) => note.pageUrl === state.source && note.breakpoint === state.breakpoint && note.targetId === message.targetId).forEach((note) => { note.documentBox = { ...message.box, x: message.box.x + state.pageScroll.x, y: message.box.y + state.pageScroll.y }; }); drawMarkup(); return; } if (_event.channel !== 'element-selected' || state.activeTab !== 'inspect') return; state.selected = message; if (!state.originalStyles.has(scopedKey(message.selector))) state.originalStyles.set(scopedKey(message.selector), message.inlineStyle); if (!state.originalTexts.has(scopedKey(message.selector))) state.originalTexts.set(scopedKey(message.selector), message.editableText); showSelection(message); controls.hidden = false; document.querySelector('#text').value = state.textChanges.get(scopedKey(message.selector)) ?? message.editableText; setControlValues({ ...message.style, ...currentChanges() }); });

document.querySelectorAll('[data-style]').forEach((control) => control.addEventListener('input', async () => { if (!state.selected) return; const property = control.dataset.style; const rawValue = control.value; if (control.type === 'color') syncHexControl(property, rawValue); const value = utils.cssValue(property, rawValue); const changes = { ...currentChanges(), [property]: value }; if (property === 'font-family' && !rawValue) delete changes[property]; state.cssTweaks.set(scopedKey(state.scope.key), changes); markControlModified(property, Object.hasOwn(changes, property)); const output = control.closest('.control-group')?.querySelector('output'); if (output) output.value = rawValue; try { const result = await executeSelected('style', { changes }); setStatus(`Preview updated: ${property} on ${result.count} element${result.count === 1 ? '' : 's'} at ${breakpoints[state.breakpoint].label}.`); } catch (error) { setStatus(error.message); } }));
document.querySelectorAll('[data-hex-for]').forEach((control) => { const applyHex = () => { const value = normalizeHex(control.value); control.setCustomValidity(value ? '' : 'Enter a hex color such as #ff0000.'); if (!value) return; control.value = value; const picker = document.querySelector(`[data-style="${control.dataset.hexFor}"]`); picker.value = value; picker.dispatchEvent(new Event('input', { bubbles: true })); }; control.addEventListener('input', applyHex); control.addEventListener('blur', applyHex); control.addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); applyHex(); } }); });
document.querySelectorAll('[data-reset-style]').forEach((button) => button.addEventListener('click', async () => { if (!state.selected) return; const property = button.dataset.resetStyle; const changes = { ...currentChanges() }; delete changes[property]; state.cssTweaks.set(scopedKey(state.scope.key), changes); try { const result = await executeSelected('reset-property', { property }); setOneControl(property, state.selected.style); setStatus(`Reset only ${property} on ${result.count} element${result.count === 1 ? '' : 's'} at ${breakpoints[state.breakpoint].label}.`); } catch (error) { setStatus(error.message); } }));
document.querySelector('#text').addEventListener('input', () => { clearTimeout(textPreviewTimer); if (!state.selected) return; const selectedTargetId = state.selected.targetId; const text = document.querySelector('#text').value; textPreviewTimer = setTimeout(async () => { if (state.selected?.targetId !== selectedTargetId) return; state.textChanges.set(scopedKey(state.selected.selector), text); try { await executeSelected('text', { text }, { exact: true }); setStatus(`Text preview updated on this element at ${breakpoints[state.breakpoint].label}.`); } catch (error) { setStatus(error.message); } }, 100); });
document.querySelector('#pinNote').addEventListener('click', () => { const note = document.querySelector('#note').value.trim(); if (!state.selected || !note) return setStatus('Select an element and enter a note first.'); state.notes.push({ pageUrl: state.source, breakpoint: state.breakpoint, viewportWidth: breakpoints[state.breakpoint].width, selector: state.selected.selector, targetId: state.selected.targetId, tag: state.selected.tag, text: state.selected.text, note, documentBox: { ...state.selected.box, x: state.selected.box.x + state.pageScroll.x, y: state.selected.box.y + state.pageScroll.y } }); document.querySelector('#note').value = ''; renderNotes(); drawMarkup(); setStatus(`Pinned feedback to the selected ${state.selected.tag} at ${breakpoints[state.breakpoint].label}.`); });
document.querySelector('#addImageNote').addEventListener('click', () => { const note = document.querySelector('#imageNote').value.trim(); if (!imageMode() || !note) return setStatus('Enter an overall image note first.'); state.notes.push({ pageUrl: state.source, breakpoint: state.breakpoint, viewportWidth: breakpoints[state.breakpoint].width, selector: 'the image as a whole', targetId: null, tag: 'image', text: 'Overall image guidance', note, documentBox: { x: 16, y: 16, width: 0, height: 0 } }); document.querySelector('#imageNote').value = ''; renderNotes(); drawMarkup(); setStatus(`Overall image note added at ${breakpoints[state.breakpoint].label}.`); });
async function resetSelected() { if (!state.selected) return; state.cssTweaks.delete(scopedKey(state.scope.key)); if (state.scope.kind === 'exact') state.textChanges.delete(scopedKey(state.selected.selector)); try { const result = await executeSelected('restore', {}); setControlValues(state.selected.style); document.querySelectorAll('[data-reset-style]').forEach((button) => { button.classList.remove('modified'); button.setAttribute('aria-pressed', 'false'); }); if (state.scope.kind === 'exact') document.querySelector('#text').value = state.originalTexts.get(scopedKey(state.selected.selector)); setStatus(`Reset ${result.count} selected element${result.count === 1 ? '' : 's'} to original values at ${breakpoints[state.breakpoint].label}.`); } catch (error) { setStatus(error.message); } }
document.querySelector('#reset').addEventListener('click', resetSelected);

document.querySelector('#reload').addEventListener('click', () => { if (state.source) open(state.source, { reload: true }); else setStatus('Open a page before reloading.'); });
back.addEventListener('click', () => { if (navigationIndex <= 0) return updateNavigationControls(); finishCurrentMarkup({ silent: true }); captureCurrentVisual().catch(() => {}); page.executeJavaScript('history.back()'); setStatus('Going back to the previous page…'); });
document.querySelector('#clearPage').addEventListener('click', () => { if (!state.source) return setStatus('No page is open.'); if (!window.confirm('Close this page and clear all preview edits, pins, markup, and handoff state?')) return; clearSession(); state.source = ''; navigationTrail = []; navigationIndex = -1; address.value = ''; page.src = 'about:blank'; document.querySelector('#empty').hidden = false; updateNavigationControls(); setStatus('Page closed. Drop or open another page when you are ready.'); });
async function captureCurrentVisual() { if (!state.source || !desktopBridge) return; const source = state.source; const breakpoint = state.breakpoint; const pageImage = await desktopBridge.capturePage(page.getWebContentsId()); const bitmap = await createImageBitmap(await (await fetch(pageImage)).blob()); const composite = document.createElement('canvas'); composite.width = bitmap.width; composite.height = bitmap.height; const compositeContext = composite.getContext('2d'); compositeContext.drawImage(bitmap, 0, 0); compositeContext.drawImage(canvas, 0, 0, composite.width, composite.height); state.annotatedImages[pageImageKey(source, breakpoint)] = composite.toDataURL('image/png'); bitmap.close(); }
async function setBreakpoint(name) { if (!breakpoints[name] || name === state.breakpoint) return; try { await captureCurrentVisual(); delete status.dataset.captureError; } catch (error) { status.dataset.captureError = error.message; } finishCurrentMarkup({ silent: true }); state.breakpoint = name; state.visitedBreakpoints.add(name); state.selected = null; state.scope = null; controls.hidden = true; document.querySelector('#selectorBar').hidden = true; selection.innerHTML = `<h2>${breakpoints[name].label} preview</h2><p>Click an element to adjust it at this size.</p>`; stage.style.setProperty('--preview-width', `${breakpoints[name].width}px`); document.querySelectorAll('[data-breakpoint]').forEach((button) => button.classList.toggle('active', button.dataset.breakpoint === name)); await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))); resizeCanvas(); let restored = null; try { if (state.source) restored = await applyCurrentBreakpoint({ reset: true }); } catch (error) { return setStatus(error.message); } renderNotes(); renderStrokes(); drawMarkup(); setStatus(`${breakpoints[name].label} preview restored ${restored?.styleTargets || 0} saved style target${restored?.styleTargets === 1 ? '' : 's'}.${status.dataset.captureError ? ` Previous image capture warning: ${status.dataset.captureError}` : ''}`); }
document.querySelectorAll('[data-breakpoint]').forEach((button) => button.addEventListener('click', () => setBreakpoint(button.dataset.breakpoint)));
address.addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); open(address.value); } });
function openDropped(event) { event.preventDefault(); event.stopPropagation(); dropHint.hidden = true; const file = event.dataTransfer.files[0]; let filePath = ''; try { if (file && desktopBridge?.pathForFile) filePath = desktopBridge.pathForFile(file); } catch {} const dropped = event.dataTransfer.getData('text/uri-list') || event.dataTransfer.getData('text/plain') || filePath; if (dropped) open(dropped.split('\n')[0]); }
address.addEventListener('dragover', (event) => event.preventDefault()); address.addEventListener('drop', openDropped); stage.addEventListener('dragenter', (event) => { event.preventDefault(); dropHint.hidden = false; }); stage.addEventListener('dragover', (event) => event.preventDefault()); stage.addEventListener('dragleave', (event) => { if (!stage.contains(event.relatedTarget)) dropHint.hidden = true; }); stage.addEventListener('drop', openDropped); page.addEventListener('dragover', (event) => { event.preventDefault(); dropHint.hidden = false; }); page.addEventListener('drop', openDropped); document.body.addEventListener('dragover', (event) => event.preventDefault()); document.body.addEventListener('drop', (event) => { if (!stage.contains(event.target)) openDropped(event); });
document.querySelector('#file').addEventListener('click', async () => { if (!desktopBridge) return open(''); const picked = await desktopBridge.chooseSource(); if (picked) open(picked); });
document.querySelector('#emptyChooseFile').addEventListener('click', () => document.querySelector('#file').click());
document.addEventListener('paste', async (event) => { const target = event.target; if (target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target?.isContentEditable) return; const hasImage = [...(event.clipboardData?.items || [])].some((item) => item.type.startsWith('image/')); if (!hasImage || !desktopBridge?.clipboardImage) return; event.preventDefault(); const imageSource = await desktopBridge.clipboardImage(); if (imageSource) open(imageSource); else setStatus('The clipboard does not contain an image.'); });
document.querySelector('#inspectTab').addEventListener('click', () => setTab('inspect')); document.querySelector('#markupTab').addEventListener('click', () => setTab('markup')); document.querySelector('#helpTab').addEventListener('click', () => setTab('help')); document.querySelector('#handoffTab').addEventListener('click', () => setTab('handoff')); document.querySelector('.tabs').addEventListener('keydown', (event) => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const buttons = [...document.querySelectorAll('.tab')]; const current = buttons.indexOf(document.activeElement); const next = event.key === 'Home' ? 0 : event.key === 'End' ? buttons.length - 1 : (current + (event.key === 'ArrowRight' ? 1 : -1) + buttons.length) % buttons.length; buttons[next].click(); buttons[next].focus(); }); document.querySelectorAll('[data-color]').forEach((button) => button.addEventListener('click', () => setAnnotationColor(button.dataset.color))); document.querySelectorAll('[data-markup-tool]').forEach((button) => button.addEventListener('click', () => { state.annotationTool = button.dataset.markupTool; document.querySelectorAll('[data-markup-tool]').forEach((choice) => choice.classList.toggle('active', choice === button)); setStatus(`${button.textContent.trim()} tool selected.`); })); document.querySelector('#annotationThickness').addEventListener('input', (event) => { state.annotationWidth = Number(event.target.value); document.querySelector('#annotationThicknessValue').value = `${state.annotationWidth} px`; }); document.querySelector('#markupExplanation').addEventListener('input', (event) => { state.markupExplanation = event.target.value; if (state.currentMarkupGroupId) state.strokes.filter((stroke) => stroke.groupId === state.currentMarkupGroupId).forEach((stroke) => { stroke.explanation = state.markupExplanation; }); document.querySelector('#markupSaved').textContent = state.currentMarkupGroupId ? 'Keep drawing, or finish this markup item to start another.' : state.markupExplanation.trim() ? 'Ready to attach. Draw one or more strokes for this markup item.' : 'Draw one or more strokes for this markup item.'; renderStrokes(); });
function finishCurrentMarkup({ silent = false } = {}) { if (!state.currentMarkupGroupId) { if (!silent) setStatus('Draw at least one stroke before finishing this markup item.'); return; } const count = state.strokes.filter((item) => item.groupId === state.currentMarkupGroupId).length; state.currentMarkupGroupId = null; state.markupExplanation = ''; document.querySelector('#markupExplanation').value = ''; document.querySelector('#markupSaved').textContent = 'Draw one or more strokes for this markup item.'; if (!silent) setStatus(`Markup item saved with ${count} stroke${count === 1 ? '' : 's'}. Draw to begin another.`); }
document.querySelector('#finishMarkup').addEventListener('click', () => finishCurrentMarkup());
let stroke; canvas.addEventListener('pointerdown', (event) => { if (!state.annotating) return; if (!state.currentMarkupGroupId) state.currentMarkupGroupId = `markup-${Date.now()}-${Math.random().toString(16).slice(2)}`; const contextId = `point-${Date.now()}`; stroke = { pageUrl: state.source, groupId: state.currentMarkupGroupId, breakpoint: state.breakpoint, viewportWidth: breakpoints[state.breakpoint].width, color: state.annotationColor, width: state.annotationWidth, tool: state.annotationTool, explanation: state.markupExplanation.trim(), anchor: null, points: [{ x: event.offsetX + state.pageScroll.x, y: event.offsetY + state.pageScroll.y }], contextId }; page.send('identify-point', { id: contextId, x: event.offsetX, y: event.offsetY }); canvas.setPointerCapture(event.pointerId); }); canvas.addEventListener('pointermove', (event) => { if (!stroke) return; const point = { x: event.offsetX + state.pageScroll.x, y: event.offsetY + state.pageScroll.y }; if (stroke.tool === 'freehand') stroke.points.push(point); else stroke.points[1] = point; drawMarkup(); }); canvas.addEventListener('pointerup', () => { if (stroke) state.strokes.push(stroke); stroke = null; const count = state.strokes.filter((item) => item.groupId === state.currentMarkupGroupId).length; document.querySelector('#markupSaved').textContent = `${count} stroke${count === 1 ? '' : 's'} in this markup item. Keep drawing, or finish it.`; renderStrokes(); drawMarkup(); });
document.querySelector('#undoStroke').addEventListener('click', () => { const index = state.strokes.findLastIndex((item) => item.pageUrl === state.source && item.breakpoint === state.breakpoint); if (index < 0) return setStatus(`No ${breakpoints[state.breakpoint].label.toLowerCase()} markup to undo.`); const groupId = state.strokes[index].groupId; state.strokes.splice(index, 1); if (!state.strokes.some((item) => item.groupId === groupId) && state.currentMarkupGroupId === groupId) state.currentMarkupGroupId = null; renderStrokes(); drawMarkup(); setStatus(`Last ${breakpoints[state.breakpoint].label.toLowerCase()} stroke removed.`); });
document.querySelector('#clearStrokes').addEventListener('click', () => { if (!currentBreakpointItems(state.strokes).length && !state.markupExplanation.trim()) return setStatus(`No ${breakpoints[state.breakpoint].label.toLowerCase()} markup to clear.`); if (!window.confirm(`Clear all ${breakpoints[state.breakpoint].label.toLowerCase()} drawing marks on this page?`)) return; state.strokes = state.strokes.filter((item) => item.pageUrl !== state.source || item.breakpoint !== state.breakpoint); state.currentMarkupGroupId = null; state.markupExplanation = ''; document.querySelector('#markupExplanation').value = ''; document.querySelector('#markupSaved').textContent = 'Draw one or more strokes for this markup item.'; renderStrokes(); drawMarkup(); setStatus(`${breakpoints[state.breakpoint].label} markup cleared on this page.`); });
function groupedMarkupFor(url) { const groups = []; state.strokes.filter((stroke) => stroke.pageUrl === url).forEach((stroke) => { let group = groups.find((item) => item.id === stroke.groupId); if (!group) { group = { id: stroke.groupId, breakpoint: stroke.breakpoint, viewportWidth: stroke.viewportWidth, explanation: stroke.explanation, strokes: [] }; groups.push(group); } group.explanation = stroke.explanation; group.strokes.push({ tool: stroke.tool || 'freehand', color: stroke.color, width: stroke.width, points: stroke.points, anchor: stroke.anchor }); }); return groups; }
async function createHandoff() { if (!desktopBridge) return setStatus('Launch AI PagePolish by PageTweaker.app to create a handoff.'); if (!state.source) return setStatus('Open a page before creating a handoff.'); finishCurrentMarkup({ silent: true }); const pages = state.pageOrder.map((url) => { const previewStyleEvidence = [...state.cssTweaks].flatMap(([key, previewValues]) => { const [pageUrl, breakpoint, rawKey] = parseScopedKey(key); if (pageUrl !== url) return []; const definition = state.scopeDefinitions.get(key); return [{ breakpoint, viewportWidth: breakpoints[breakpoint].width, selector: definition?.selector || rawKey.replace(/^exact:/, ''), selectorScope: definition?.kind || 'exact', previewValues, meaning: 'Visual evidence of the desired result, not prescribed implementation code.' }]; }); const previewTextEvidence = [...state.textChanges].flatMap(([key, previewText]) => { const [pageUrl, breakpoint, selector] = parseScopedKey(key); return pageUrl === url ? [{ breakpoint, viewportWidth: breakpoints[breakpoint].width, selector, previewText, meaning: 'Desired wording and visible outcome; integrate it through the real project structure.' }] : []; }); return { url, previewStyleEvidence, previewTextEvidence, feedbackNotes: state.notes.filter((item) => item.pageUrl === url), markup: groupedMarkupFor(url), annotatedImages: Object.keys(state.annotatedImages).filter((key) => key.startsWith(`page-${state.pageOrder.indexOf(url) + 1}-`)).map((key) => `${key}-annotated.png`) }; }); const handoff = { version: 6, exportedAt: new Date().toISOString(), source: state.pageOrder[0], currentPage: state.source, intent: 'User feedback and desired visual outcomes, separated by page URL. Evidence is not a prescribed implementation.', breakpoints, pages }; try { setStatus('Capturing the current page context for the feedback brief…'); await captureCurrentVisual(); pages[state.pageOrder.indexOf(state.source)].annotatedImages = Object.keys(state.annotatedImages).filter((key) => key.startsWith(`page-${state.pageOrder.indexOf(state.source) + 1}-`)).map((key) => `${key}-annotated.png`); const result = await desktopBridge.exportBundle({ handoff, prompt: makePrompt(handoff), annotatedImages: state.annotatedImages }); state.handoffPath = result.path; document.querySelector('#handoffName').textContent = result.name; document.querySelector('#handoffPath').value = result.path; document.querySelector('#handoffEmpty').hidden = true; document.querySelector('#handoffReady').hidden = false; setTab('handoff', { silent: true }); setStatus('Feedback brief ready. Drag the file into your AI chat or copy its full path.'); } catch (error) { setStatus(`Handoff failed: ${error.message}`); } }
document.querySelector('#export').addEventListener('click', createHandoff); document.querySelector('#createHandoff').addEventListener('click', createHandoff);
document.querySelector('#handoffFile').addEventListener('dragstart', (event) => { event.preventDefault(); if (state.handoffPath) desktopBridge.startDrag(state.handoffPath); });
document.querySelector('#copyHandoffPath').addEventListener('click', async () => { if (!state.handoffPath) return; await desktopBridge.copyText(state.handoffPath); setStatus('Handoff path copied. Paste it into your AI chat.'); });
document.querySelectorAll('.bookmarklet').forEach((bookmarklet) => bookmarklet.addEventListener('click', async (event) => { event.preventDefault(); const code = event.currentTarget.getAttribute('href'); if (!desktopBridge) return setStatus('Drag this bookmarklet to Chrome’s bookmarks bar.'); await desktopBridge.copyText(code); setStatus('Chrome launcher copied. Create a bookmark in Chrome and paste this into its URL field.'); }));
document.querySelector('#showHandoff').addEventListener('click', () => { if (state.handoffPath) desktopBridge.showInFolder(state.handoffPath); });
renderStrokes(); window.addEventListener('resize', resizeCanvas); page.setAttribute('preload', new URL('page-preload.cjs', location.href).href); const initial = new URLSearchParams(location.search).get('source'); if (initial) open(initial); if (desktopBridge) { desktopBridge.version().then((value) => { document.querySelector('#version').textContent = `v${value}`; }); desktopBridge.onOpenSource(open); desktopBridge.onPreviewRequestError(({ origin, error }) => setStatus(`The page could not reach ${origin}: ${error}. No password or request contents were recorded.`)); } else setStatus('Launch AI PagePolish by PageTweaker.app to open pages, select elements, pin notes, and export bundles.');
