const page = document.querySelector('#page');
const address = document.querySelector('#address');
const status = document.querySelector('#status');
const controls = document.querySelector('#controls');
const selection = document.querySelector('#selection');
const canvas = document.querySelector('#markup');
const ctx = canvas.getContext('2d');
const stage = document.querySelector('#stage');
const dropHint = document.querySelector('#dropHint');
const aside = document.querySelector('aside');
const utils = window.PageTweakerUtils;
const desktopBridge = window.pageTweaker;
const breakpoints = { desktop: { label: 'Desktop', width: 1440 }, tablet: { label: 'Tablet', width: 834 }, mobile: { label: 'Mobile', width: 390 } };
const state = { source: '', breakpoint: 'desktop', visitedBreakpoints: new Set(['desktop']), annotatedImages: {}, pageScroll: { x: 0, y: 0 }, selected: null, scope: null, scopeDefinitions: new Map(), cssTweaks: new Map(), textChanges: new Map(), originalStyles: new Map(), originalTexts: new Map(), notes: [], strokes: [], markupExplanation: '', handoffPath: '', activeTab: 'inspect', annotating: false, annotationColor: '#f25f5c', annotationWidth: 3 };
const pendingEdits = new Map();
const pendingSessions = new Map();

function setStatus(message) { status.textContent = message; }
function hasSessionWork() { return state.cssTweaks.size || state.textChanges.size || state.notes.length || state.strokes.length || state.markupExplanation.trim(); }
function makePrompt(handoff) { const sections = Object.keys(breakpoints).map((breakpoint) => { const styles = handoff.previewStyleEvidence.filter((item) => item.breakpoint === breakpoint).map((item) => `- Visual target near \`${item.selector}\`: ${Object.entries(item.previewValues).map(([name, value]) => `${name} ${value}`).join(', ')}.`); const texts = handoff.previewTextEvidence.filter((item) => item.breakpoint === breakpoint).map((item) => `- Desired text near \`${item.selector}\`: “${item.previewText}”`); const notes = handoff.feedbackNotes.filter((item) => item.breakpoint === breakpoint).map((item) => `- Feedback near \`${item.selector}\`: ${item.note}`); const marks = handoff.markup.filter((item) => item.breakpoint === breakpoint).map((item) => `- Drawn feedback near \`${item.anchor?.selector || 'the recorded page coordinates'}\`: ${item.explanation || 'No explanation was entered.'}`); const items = [...styles, ...texts, ...notes, ...marks]; return items.length ? `## ${breakpoints[breakpoint].label} feedback (${breakpoints[breakpoint].width}px preview)\n\n${items.join('\n')}` : ''; }).filter(Boolean).join('\n\n'); return `# Page Tweaker feedback brief for an AI agent\n\nThe user used Page Tweaker to try changes visually before asking you to modify the real project. This archive records what they want the result to look and feel like at desktop, tablet, and mobile sizes.\n\n## Important implementation rule\n\nTreat selectors, element names, current values, preview values, coordinates, and replacement text as evidence describing the user's desired outcome. They identify what the user was looking at; they do not prescribe the final code structure. Inspect the actual project and choose the implementation that fits its existing components, CSS system, responsive rules, accessibility requirements, and conventions. Do not blindly paste selectors, create elements merely because a selector names one, or treat preview values as a request to replace the project's responsive architecture. Preserve unrelated work.\n\n${sections || 'No feedback items were recorded.'}\n\n## Files\n\nRead \`handoff.json\` for complete evidence and breakpoint metadata. Files such as \`desktop-annotated.png\`, \`tablet-annotated.png\`, and \`mobile-annotated.png\` show the actual page underneath the user's marks for every preview size they visited. The per-mark explanation and nearby element locator carry the intended meaning. First infer the desired outcome, then implement it appropriately in the real system and verify the result at every referenced breakpoint.`; }
function scopedKey(key) { return `${state.breakpoint}|${key}`; }
function currentBreakpointItems(items) { return items.filter((item) => item.breakpoint === state.breakpoint); }
function resizeCanvas() { const box = page.getBoundingClientRect(); canvas.width = box.width * devicePixelRatio; canvas.height = box.height * devicePixelRatio; canvas.style.width = `${box.width}px`; canvas.style.height = `${box.height}px`; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); drawMarkup(); }
function drawMarkup() { const box = page.getBoundingClientRect(); ctx.clearRect(0, 0, box.width, box.height); for (const stroke of currentBreakpointItems(state.strokes)) { ctx.strokeStyle = stroke.color; ctx.lineWidth = stroke.width; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); stroke.points.forEach((point, index) => { const x = point.x - state.pageScroll.x; const y = point.y - state.pageScroll.y; index ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); } currentBreakpointItems(state.notes).forEach((note, index) => { const x = note.documentBox.x - state.pageScroll.x; const y = note.documentBox.y - state.pageScroll.y; if (x < -25 || y < -25 || x > box.width || y > box.height) return; ctx.fillStyle = '#ffca56'; ctx.beginPath(); ctx.arc(x + 10, y + 10, 10, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#161616'; ctx.font = '11px sans-serif'; ctx.fillText(String(index + 1), x + 7, y + 14); }); }
function renderNotes() { const list = document.querySelector('#notes'); list.replaceChildren(); currentBreakpointItems(state.notes).forEach((note, index) => { const item = document.createElement('div'); item.className = 'note'; const title = document.createElement('strong'); title.textContent = `${index + 1}. ${breakpoints[note.breakpoint].label}: pinned to ${note.tag}`; item.append(title, document.createElement('br'), document.createTextNode(note.text || note.selector), document.createElement('br'), document.createTextNode(note.note)); list.append(item); }); }
function renderStrokes() { const list = document.querySelector('#strokeList'); list.replaceChildren(); const strokes = state.strokes.map((stroke, index) => ({ stroke, index })).filter(({ stroke }) => stroke.breakpoint === state.breakpoint); if (!strokes.length) { const empty = document.createElement('p'); empty.className = 'hint'; empty.textContent = `No ${breakpoints[state.breakpoint].label.toLowerCase()} drawing strokes yet.`; list.append(empty); return; } strokes.forEach(({ stroke, index }, visibleIndex) => { const item = document.createElement('div'); item.className = 'stroke-item stroke-detail'; const heading = document.createElement('span'); const color = document.createElement('i'); color.style.background = stroke.color; heading.append(color, document.createTextNode(` Mark ${visibleIndex + 1} · ${breakpoints[stroke.breakpoint].label}`)); const remove = document.createElement('button'); remove.textContent = 'Remove'; remove.title = 'Remove this mark'; remove.addEventListener('click', () => { state.strokes.splice(index, 1); renderStrokes(); drawMarkup(); setStatus('Markup mark removed.'); }); const explanation = document.createElement('textarea'); explanation.value = stroke.explanation; explanation.placeholder = 'Explain what this mark means'; explanation.addEventListener('input', () => { stroke.explanation = explanation.value; }); item.append(heading, remove, explanation); list.append(item); }); }
function clearSession() { state.breakpoint = 'desktop'; state.visitedBreakpoints = new Set(['desktop']); state.annotatedImages = {}; state.pageScroll = { x: 0, y: 0 }; state.selected = null; state.scope = null; state.scopeDefinitions.clear(); state.cssTweaks.clear(); state.textChanges.clear(); state.originalStyles.clear(); state.originalTexts.clear(); state.notes = []; state.strokes = []; state.markupExplanation = ''; state.handoffPath = ''; stage.style.setProperty('--preview-width', `${breakpoints.desktop.width}px`); document.querySelectorAll('[data-breakpoint]').forEach((button) => button.classList.toggle('active', button.dataset.breakpoint === 'desktop')); controls.hidden = true; selection.innerHTML = '<h2>Select an element</h2><p>Click anything in the preview to adjust it.</p>'; document.querySelector('#selectorBar').hidden = true; document.querySelector('#notes').innerHTML = ''; document.querySelector('#text').value = ''; document.querySelector('#note').value = ''; document.querySelector('#markupExplanation').value = ''; document.querySelector('#handoffEmpty').hidden = false; document.querySelector('#handoffReady').hidden = true; setTab('inspect', { silent: true }); renderStrokes(); drawMarkup(); }
function setTab(tab, { silent = false } = {}) { const panels = { inspect: 'inspectPanel', markup: 'annotationControls', help: 'helpPanel', handoff: 'handoffPanel' }; const tabs = { inspect: 'inspectTab', markup: 'markupTab', help: 'helpTab', handoff: 'handoffTab' }; state.activeTab = tab; state.annotating = tab === 'markup'; canvas.style.pointerEvents = state.annotating ? 'auto' : 'none'; if (state.source) page.send('set-inspector', tab === 'inspect'); Object.entries(panels).forEach(([name, id]) => { document.querySelector(`#${id}`).hidden = name !== tab; }); Object.entries(tabs).forEach(([name, id]) => { const button = document.querySelector(`#${id}`); const active = name === tab; button.classList.toggle('active', active); button.setAttribute('aria-selected', String(active)); button.tabIndex = active ? 0 : -1; }); aside.scrollTop = 0; if (!silent) setStatus(tab === 'markup' ? `Markup mode at ${breakpoints[state.breakpoint].label}: explain the next mark, then draw it.` : tab === 'help' ? 'Learn how to preview feedback and give the resulting brief to an AI session.' : tab === 'handoff' ? 'Create or share the complete feedback file with your AI session.' : `Inspect mode at ${breakpoints[state.breakpoint].label}: click an element to adjust it.`); }
function open(rawValue, { reload = false } = {}) { if (!desktopBridge) return setStatus('Launch Page Tweaker.app. Opening src/index.html directly in a browser cannot inspect elements or export bundles.'); const source = reload ? state.source : utils.normalizeSource(rawValue); if (!source) return setStatus('Paste a file:// URL, public http(s) URL, or path to an .html file.'); const sameSource = source === state.source; const replacing = Boolean(state.source) && (reload || !sameSource || hasSessionWork()); if (replacing && !window.confirm(`Load ${reload ? 'this page again' : 'the new page'}? This clears this page’s preview edits, pins, and markup.`)) { address.value = state.source; return; } clearSession(); state.source = source; address.value = source; document.querySelector('#empty').hidden = true; if (reload || sameSource) page.reloadIgnoringCache(); else page.src = source; setStatus(reload || sameSource ? 'Reloading a clean preview…' : 'Loading a fresh preview…'); }
function currentChanges() { return state.scope ? state.cssTweaks.get(scopedKey(state.scope.key)) || {} : {}; }
function executeSelected(action, payload, { exact = false } = {}) { const id = `edit-${Date.now()}-${Math.random().toString(16).slice(2)}`; const scope = exact ? state.selected.scopes[0] : state.scope; return new Promise((resolve, reject) => { const timeout = setTimeout(() => { pendingEdits.delete(id); reject(new Error('The page did not acknowledge the change. Select the element again.')); }, 1500); pendingEdits.set(id, { resolve, reject, timeout }); page.send('apply-edit', { id, action, targetId: state.selected.targetId, scope, ...payload }); }); }
function setControlValues(style) { document.querySelectorAll('[data-style]').forEach((control) => { const property = control.dataset.style; const rawValue = utils.readableValue(style, property) || ''; if (control.tagName === 'SELECT') { control.value = currentChanges()[property] || ''; return; } if (control.type === 'color') { const match = rawValue.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/); control.value = match ? `#${[match[1], match[2], match[3]].map((value) => Number(value).toString(16).padStart(2, '0')).join('')}` : '#000000'; return; } const bounds = utils.sliderBounds(property, rawValue); control.min = bounds.min; control.max = bounds.max; control.step = bounds.step; control.value = bounds.value; const output = control.closest('.control-group')?.querySelector('output'); if (output) output.value = bounds.value; }); }
function setOneControl(property, style) { const control = document.querySelector(`[data-style="${property}"]`); if (!control) return; const rawValue = utils.readableValue(style, property) || ''; if (control.tagName === 'SELECT') control.value = ''; else if (control.type === 'color') { const match = rawValue.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/); control.value = match ? `#${[match[1], match[2], match[3]].map((value) => Number(value).toString(16).padStart(2, '0')).join('')}` : '#000000'; } else { const bounds = utils.sliderBounds(property, rawValue); control.min = bounds.min; control.max = bounds.max; control.step = bounds.step; control.value = bounds.value; const output = control.closest('.control-group')?.querySelector('output'); if (output) output.value = bounds.value; } }
function setScope(scope) { state.scope = scope; state.scopeDefinitions.set(scopedKey(scope.key), scope); document.querySelectorAll('[data-scope-key]').forEach((button) => button.classList.toggle('active', button.dataset.scopeKey === scope.key)); document.querySelector('#scopeSummary').textContent = scope.kind === 'exact' ? `Changes affect only this element at ${breakpoints[state.breakpoint].label}.` : `Changes affect ${scope.count} matching elements at ${breakpoints[state.breakpoint].label}.`; setControlValues({ ...state.selected.style, ...currentChanges() }); setStatus(scope.kind === 'exact' ? `Editing this element only at ${breakpoints[state.breakpoint].label}.` : `Editing all ${scope.count} elements matching ${scope.selector} at ${breakpoints[state.breakpoint].label}.`); }
function showSelection(selected) { selection.replaceChildren(); const heading = document.createElement('h2'); heading.textContent = `Selected: ${selected.tag}`; const excerpt = document.createElement('p'); excerpt.textContent = selected.text || 'No readable text'; selection.append(heading, excerpt); document.querySelector('#pinContext').textContent = `This note will stay attached to this ${selected.tag} while the page scrolls.`; const bar = document.querySelector('#selectorBar'); bar.hidden = false; const choices = document.querySelector('#scopeChoices'); choices.replaceChildren(); selected.scopes.forEach((scope) => { const button = document.createElement('button'); button.dataset.scopeKey = scope.key; button.title = scope.selector; button.textContent = `${scope.label}${scope.kind === 'all' ? ` (${scope.count})` : ''}`; button.addEventListener('click', () => setScope(scope)); choices.append(button); }); document.querySelector('#selectorPath').textContent = selected.selector; setScope(selected.scopes[0]); }
function setAnnotationColor(color) { state.annotationColor = color; document.querySelectorAll('[data-color]').forEach((button) => button.classList.toggle('active', button.dataset.color === color)); }

function applyCurrentBreakpoint({ reset = false } = {}) { const prefix = `${state.breakpoint}|`; const styles = [...state.cssTweaks].filter(([key]) => key.startsWith(prefix)).map(([key, changes]) => ({ selector: state.scopeDefinitions.get(key)?.selector || key.slice(prefix.length).replace(/^exact:/, ''), changes })); const texts = [...state.textChanges].filter(([key]) => key.startsWith(prefix)).map(([key, text]) => ({ selector: key.slice(prefix.length), text })); const id = `session-${Date.now()}-${Math.random().toString(16).slice(2)}`; return new Promise((resolve, reject) => { const timeout = setTimeout(() => { pendingSessions.delete(id); reject(new Error('The preview did not finish restoring this breakpoint.')); }, 2000); pendingSessions.set(id, { resolve, reject, timeout }); page.send('apply-session', { id, reset, styles, texts }); }); }
page.addEventListener('did-finish-load', () => { state.pageScroll = { x: 0, y: 0 }; page.send('set-inspector', state.activeTab === 'inspect'); applyCurrentBreakpoint().catch(() => {}); resizeCanvas(); renderNotes(); renderStrokes(); setStatus(state.activeTab === 'inspect' ? `Click an element to inspect and tweak the ${breakpoints[state.breakpoint].label.toLowerCase()} preview.` : 'Page loaded. Choose Inspect to select an element.'); });
page.addEventListener('ipc-message', (_event) => { const [message] = _event.args; if (_event.channel === 'edit-result') { const pending = pendingEdits.get(message.id); if (!pending) return; clearTimeout(pending.timeout); pendingEdits.delete(message.id); message.ok ? pending.resolve(message) : pending.reject(new Error(message.message)); return; } if (_event.channel === 'session-applied') { const pending = pendingSessions.get(message.id); if (!pending) return; clearTimeout(pending.timeout); pendingSessions.delete(message.id); message.ok ? pending.resolve(message) : pending.reject(new Error(message.message)); return; } if (_event.channel === 'page-scroll') { state.pageScroll = message; drawMarkup(); return; } if (_event.channel === 'point-context') { const targetStroke = stroke?.contextId === message.id ? stroke : state.strokes.find((item) => item.contextId === message.id); if (targetStroke) targetStroke.anchor = { selector: message.selector, tag: message.tag, text: message.text }; return; } if (_event.channel === 'element-position') { if (state.selected?.targetId === message.targetId) state.selected.box = message.box; state.notes.filter((note) => note.breakpoint === state.breakpoint && note.targetId === message.targetId).forEach((note) => { note.documentBox = { ...message.box, x: message.box.x + state.pageScroll.x, y: message.box.y + state.pageScroll.y }; }); drawMarkup(); return; } if (_event.channel !== 'element-selected' || state.activeTab !== 'inspect') return; state.selected = message; if (!state.originalStyles.has(message.selector)) state.originalStyles.set(message.selector, message.inlineStyle); if (!state.originalTexts.has(message.selector)) state.originalTexts.set(message.selector, message.text); showSelection(message); controls.hidden = false; document.querySelector('#text').value = state.textChanges.get(scopedKey(message.selector)) ?? message.text; setControlValues({ ...message.style, ...currentChanges() }); });

document.querySelectorAll('[data-style]').forEach((control) => control.addEventListener('input', async () => { if (!state.selected) return; const property = control.dataset.style; const rawValue = control.value; const value = utils.cssValue(property, rawValue); const changes = { ...currentChanges(), [property]: value }; if (property === 'font-family' && !rawValue) delete changes[property]; state.cssTweaks.set(scopedKey(state.scope.key), changes); const output = control.closest('.control-group')?.querySelector('output'); if (output) output.value = rawValue; try { const result = await executeSelected('style', { changes }); setStatus(`Preview updated: ${property} on ${result.count} element${result.count === 1 ? '' : 's'} at ${breakpoints[state.breakpoint].label}.`); } catch (error) { setStatus(error.message); } }));
document.querySelectorAll('[data-reset-style]').forEach((button) => button.addEventListener('click', async () => { if (!state.selected) return; const property = button.dataset.resetStyle; const changes = { ...currentChanges() }; delete changes[property]; state.cssTweaks.set(scopedKey(state.scope.key), changes); try { const result = await executeSelected('reset-property', { property }); setOneControl(property, state.selected.style); setStatus(`Reset only ${property} on ${result.count} element${result.count === 1 ? '' : 's'} at ${breakpoints[state.breakpoint].label}.`); } catch (error) { setStatus(error.message); } }));
document.querySelector('#applyText').addEventListener('click', async () => { if (!state.selected) return; const text = document.querySelector('#text').value; state.textChanges.set(scopedKey(state.selected.selector), text); try { await executeSelected('text', { text }, { exact: true }); setStatus(`Text preview updated on this element at ${breakpoints[state.breakpoint].label}.`); } catch (error) { setStatus(error.message); } });
document.querySelector('#pinNote').addEventListener('click', () => { const note = document.querySelector('#note').value.trim(); if (!state.selected || !note) return setStatus('Select an element and enter a note first.'); state.notes.push({ breakpoint: state.breakpoint, viewportWidth: breakpoints[state.breakpoint].width, selector: state.selected.selector, targetId: state.selected.targetId, tag: state.selected.tag, text: state.selected.text, note, documentBox: { ...state.selected.box, x: state.selected.box.x + state.pageScroll.x, y: state.selected.box.y + state.pageScroll.y } }); document.querySelector('#note').value = ''; renderNotes(); drawMarkup(); setStatus(`Pinned feedback to the selected ${state.selected.tag} at ${breakpoints[state.breakpoint].label}.`); });
async function resetSelected() { if (!state.selected) return; state.cssTweaks.delete(scopedKey(state.scope.key)); if (state.scope.kind === 'exact') state.textChanges.delete(scopedKey(state.selected.selector)); try { const result = await executeSelected('restore', {}); setControlValues(state.selected.style); if (state.scope.kind === 'exact') document.querySelector('#text').value = state.originalTexts.get(state.selected.selector); setStatus(`Reset ${result.count} selected element${result.count === 1 ? '' : 's'} to original values at ${breakpoints[state.breakpoint].label}.`); } catch (error) { setStatus(error.message); } }
document.querySelector('#reset').addEventListener('click', resetSelected);

document.querySelector('#reload').addEventListener('click', () => { if (state.source) open(state.source, { reload: true }); else setStatus('Open a page before reloading.'); });
async function captureCurrentVisual() { if (!state.source || !desktopBridge) return; const pageImage = await desktopBridge.capturePage(page.getWebContentsId()); const bitmap = await createImageBitmap(await (await fetch(pageImage)).blob()); const composite = document.createElement('canvas'); composite.width = bitmap.width; composite.height = bitmap.height; const compositeContext = composite.getContext('2d'); compositeContext.drawImage(bitmap, 0, 0); compositeContext.drawImage(canvas, 0, 0, composite.width, composite.height); state.annotatedImages[state.breakpoint] = composite.toDataURL('image/png'); bitmap.close(); }
async function setBreakpoint(name) { if (!breakpoints[name] || name === state.breakpoint) return; try { await captureCurrentVisual(); delete status.dataset.captureError; } catch (error) { status.dataset.captureError = error.message; } state.breakpoint = name; state.visitedBreakpoints.add(name); state.selected = null; state.scope = null; controls.hidden = true; document.querySelector('#selectorBar').hidden = true; selection.innerHTML = `<h2>${breakpoints[name].label} preview</h2><p>Click an element to adjust it at this size.</p>`; document.querySelector('#markupExplanation').value = ''; state.markupExplanation = ''; stage.style.setProperty('--preview-width', `${breakpoints[name].width}px`); document.querySelectorAll('[data-breakpoint]').forEach((button) => button.classList.toggle('active', button.dataset.breakpoint === name)); await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))); resizeCanvas(); let restored = null; try { if (state.source) restored = await applyCurrentBreakpoint({ reset: true }); } catch (error) { return setStatus(error.message); } renderNotes(); renderStrokes(); drawMarkup(); setStatus(`${breakpoints[name].label} preview restored ${restored?.styleTargets || 0} saved style target${restored?.styleTargets === 1 ? '' : 's'}.${status.dataset.captureError ? ` Previous image capture warning: ${status.dataset.captureError}` : ''}`); }
document.querySelectorAll('[data-breakpoint]').forEach((button) => button.addEventListener('click', () => setBreakpoint(button.dataset.breakpoint)));
address.addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); open(address.value); } });
function openDropped(event) { event.preventDefault(); event.stopPropagation(); dropHint.hidden = true; const dropped = event.dataTransfer.getData('text/uri-list') || event.dataTransfer.getData('text/plain') || event.dataTransfer.files[0]?.path; if (dropped) open(dropped.split('\n')[0]); }
address.addEventListener('dragover', (event) => event.preventDefault()); address.addEventListener('drop', openDropped); stage.addEventListener('dragenter', (event) => { event.preventDefault(); dropHint.hidden = false; }); stage.addEventListener('dragover', (event) => event.preventDefault()); stage.addEventListener('dragleave', (event) => { if (!stage.contains(event.relatedTarget)) dropHint.hidden = true; }); stage.addEventListener('drop', openDropped); page.addEventListener('dragover', (event) => { event.preventDefault(); dropHint.hidden = false; }); page.addEventListener('drop', openDropped); document.body.addEventListener('dragover', (event) => event.preventDefault()); document.body.addEventListener('drop', (event) => { if (!stage.contains(event.target)) openDropped(event); });
document.querySelector('#file').addEventListener('click', async () => { if (!desktopBridge) return open(''); const picked = await desktopBridge.chooseSource(); if (picked) open(picked); });
document.querySelector('#inspectTab').addEventListener('click', () => setTab('inspect')); document.querySelector('#markupTab').addEventListener('click', () => setTab('markup')); document.querySelector('#helpTab').addEventListener('click', () => setTab('help')); document.querySelector('#handoffTab').addEventListener('click', () => setTab('handoff')); document.querySelector('.tabs').addEventListener('keydown', (event) => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const buttons = [...document.querySelectorAll('.tab')]; const current = buttons.indexOf(document.activeElement); const next = event.key === 'Home' ? 0 : event.key === 'End' ? buttons.length - 1 : (current + (event.key === 'ArrowRight' ? 1 : -1) + buttons.length) % buttons.length; buttons[next].click(); buttons[next].focus(); }); document.querySelectorAll('[data-color]').forEach((button) => button.addEventListener('click', () => setAnnotationColor(button.dataset.color))); document.querySelector('#annotationThickness').addEventListener('input', (event) => { state.annotationWidth = Number(event.target.value); document.querySelector('#annotationThicknessValue').value = `${state.annotationWidth} px`; }); document.querySelector('#markupExplanation').addEventListener('input', (event) => { state.markupExplanation = event.target.value; document.querySelector('#markupSaved').textContent = state.markupExplanation.trim() ? 'Ready to attach to your next line.' : 'This explanation will attach to the next line you draw.'; });
let stroke; canvas.addEventListener('pointerdown', (event) => { if (!state.annotating) return; const contextId = `point-${Date.now()}`; stroke = { breakpoint: state.breakpoint, viewportWidth: breakpoints[state.breakpoint].width, color: state.annotationColor, width: state.annotationWidth, explanation: state.markupExplanation.trim(), anchor: null, points: [{ x: event.offsetX + state.pageScroll.x, y: event.offsetY + state.pageScroll.y }], contextId }; page.send('identify-point', { id: contextId, x: event.offsetX, y: event.offsetY }); canvas.setPointerCapture(event.pointerId); }); canvas.addEventListener('pointermove', (event) => { if (!stroke) return; stroke.points.push({ x: event.offsetX + state.pageScroll.x, y: event.offsetY + state.pageScroll.y }); drawMarkup(); ctx.strokeStyle = stroke.color; ctx.lineWidth = stroke.width; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); stroke.points.forEach((point, index) => { const x = point.x - state.pageScroll.x; const y = point.y - state.pageScroll.y; index ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); }); canvas.addEventListener('pointerup', () => { if (stroke) state.strokes.push(stroke); stroke = null; state.markupExplanation = ''; document.querySelector('#markupExplanation').value = ''; document.querySelector('#markupSaved').textContent = 'This explanation will attach to the next line you draw.'; renderStrokes(); drawMarkup(); });
document.querySelector('#undoStroke').addEventListener('click', () => { const index = state.strokes.findLastIndex((item) => item.breakpoint === state.breakpoint); if (index < 0) return setStatus(`No ${breakpoints[state.breakpoint].label.toLowerCase()} markup to undo.`); state.strokes.splice(index, 1); renderStrokes(); drawMarkup(); setStatus(`Last ${breakpoints[state.breakpoint].label.toLowerCase()} mark removed.`); });
document.querySelector('#clearStrokes').addEventListener('click', () => { if (!currentBreakpointItems(state.strokes).length && !state.markupExplanation.trim()) return setStatus(`No ${breakpoints[state.breakpoint].label.toLowerCase()} markup to clear.`); if (!window.confirm(`Clear all ${breakpoints[state.breakpoint].label.toLowerCase()} drawing marks?`)) return; state.strokes = state.strokes.filter((item) => item.breakpoint !== state.breakpoint); state.markupExplanation = ''; document.querySelector('#markupExplanation').value = ''; document.querySelector('#markupSaved').textContent = 'This explanation will attach to the next line you draw.'; renderStrokes(); drawMarkup(); setStatus(`${breakpoints[state.breakpoint].label} markup cleared.`); });
async function createHandoff() { if (!desktopBridge) return setStatus('Launch Page Tweaker.app to create a handoff.'); if (!state.source) return setStatus('Open a page before creating a handoff.'); const previewStyleEvidence = [...state.cssTweaks].map(([key, previewValues]) => { const [breakpoint, rawKey] = key.split('|'); const definition = state.scopeDefinitions.get(key); return { breakpoint, viewportWidth: breakpoints[breakpoint].width, selector: definition?.selector || rawKey.replace(/^exact:/, ''), selectorScope: definition?.kind || 'exact', previewValues, meaning: 'Visual evidence of the desired result, not prescribed implementation code.' }; }); const previewTextEvidence = [...state.textChanges].map(([key, previewText]) => { const separator = key.indexOf('|'); const breakpoint = key.slice(0, separator); return { breakpoint, viewportWidth: breakpoints[breakpoint].width, selector: key.slice(separator + 1), previewText, meaning: 'Desired wording and visible outcome; integrate it through the real project structure.' }; }); const handoff = { version: 5, exportedAt: new Date().toISOString(), source: state.source, intent: 'User feedback and desired visual outcomes. Evidence is not a prescribed implementation.', breakpoints, previewStyleEvidence, previewTextEvidence, feedbackNotes: state.notes, markup: state.strokes }; try { setStatus('Capturing the page context for the feedback brief…'); await captureCurrentVisual(); const result = await desktopBridge.exportBundle({ handoff, prompt: makePrompt(handoff), annotatedImages: state.annotatedImages }); state.handoffPath = result.path; document.querySelector('#handoffName').textContent = result.name; document.querySelector('#handoffPath').value = result.path; document.querySelector('#handoffEmpty').hidden = true; document.querySelector('#handoffReady').hidden = false; setTab('handoff', { silent: true }); setStatus('Feedback brief ready. Drag the file into your AI chat or copy its full path.'); } catch (error) { setStatus(`Handoff failed: ${error.message}`); } }
document.querySelector('#export').addEventListener('click', createHandoff); document.querySelector('#createHandoff').addEventListener('click', createHandoff);
document.querySelector('#handoffFile').addEventListener('dragstart', (event) => { event.preventDefault(); if (state.handoffPath) desktopBridge.startDrag(state.handoffPath); });
document.querySelector('#copyHandoffPath').addEventListener('click', async () => { if (!state.handoffPath) return; await desktopBridge.copyText(state.handoffPath); setStatus('Handoff path copied. Paste it into your AI chat.'); });
document.querySelector('#showHandoff').addEventListener('click', () => { if (state.handoffPath) desktopBridge.showInFolder(state.handoffPath); });
renderStrokes(); window.addEventListener('resize', resizeCanvas); page.setAttribute('preload', new URL('page-preload.cjs', location.href).href); const initial = new URLSearchParams(location.search).get('source'); if (initial) open(initial); if (desktopBridge) { desktopBridge.version().then((value) => { document.querySelector('#version').textContent = `v${value}`; }); desktopBridge.onOpenSource(open); } else setStatus('Launch Page Tweaker.app to open pages, select elements, pin notes, and export bundles.');
