const page = document.querySelector('#page');
const address = document.querySelector('#address');
const status = document.querySelector('#status');
const controls = document.querySelector('#controls');
const selection = document.querySelector('#selection');
const canvas = document.querySelector('#markup');
const ctx = canvas.getContext('2d');
const stage = document.querySelector('#stage');
const dropHint = document.querySelector('#dropHint');
const aside = document.querySelector('aside');
const utils = window.PageTweakerUtils;
const desktopBridge = window.pageTweaker;
const state = { source: '', selected: null, cssTweaks: new Map(), textChanges: new Map(), originalStyles: new Map(), originalTexts: new Map(), notes: [], strokes: [], annotating: false, annotationColor: '#f25f5c', annotationWidth: 3 };
const pendingEdits = new Map();

function setStatus(message) { status.textContent = message; }
function hasSessionWork() { return state.cssTweaks.size || state.textChanges.size || state.notes.length || state.strokes.length; }
function makePrompt(handoff) { return `# Page Tweaker handoff\n\nApply these preview-validated changes to the source artifact. Preserve unrelated work.\n\n- Source: ${handoff.source}\n- CSS tweaks: ${handoff.cssTweaks.length}\n- Text changes: ${handoff.textChanges.length}\n- Notes: ${handoff.notes.length}\n\nRead \`handoff.json\` for element locators and exact values. Review \`annotated.png\` for visual markup before implementing.`; }
function resizeCanvas() { const box = page.getBoundingClientRect(); canvas.width = box.width * devicePixelRatio; canvas.height = box.height * devicePixelRatio; canvas.style.width = `${box.width}px`; canvas.style.height = `${box.height}px`; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); drawMarkup(); }
function drawMarkup() { const box = page.getBoundingClientRect(); ctx.clearRect(0, 0, box.width, box.height); for (const stroke of state.strokes) { ctx.strokeStyle = stroke.color; ctx.lineWidth = stroke.width; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); stroke.points.forEach((point, index) => index ? ctx.lineTo(point.x, point.y) : ctx.moveTo(point.x, point.y)); ctx.stroke(); } state.notes.forEach((note, index) => { const { x, y } = note.box; if (x < -25 || y < -25 || x > box.width || y > box.height) return; ctx.fillStyle = '#ffca56'; ctx.beginPath(); ctx.arc(x + 10, y + 10, 10, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#161616'; ctx.font = '11px sans-serif'; ctx.fillText(String(index + 1), x + 7, y + 14); }); }
function renderNotes() { document.querySelector('#notes').innerHTML = state.notes.map((note, index) => `<div class="note"><strong>${index + 1}. Pinned to ${note.tag}</strong><br>${note.text || note.selector}<br>${note.note}</div>`).join(''); }
function clearSession() { state.selected = null; state.cssTweaks.clear(); state.textChanges.clear(); state.originalStyles.clear(); state.originalTexts.clear(); state.notes = []; state.strokes = []; controls.hidden = true; selection.innerHTML = '<h2>Select an element</h2><p>Click anything in the preview to adjust it.</p>'; document.querySelector('#notes').innerHTML = ''; document.querySelector('#text').value = ''; document.querySelector('#note').value = ''; drawMarkup(); }
function setTab(tab) { const markup = tab === 'markup'; document.querySelector('#inspectPanel').hidden = markup; document.querySelector('#annotationControls').hidden = !markup; document.querySelector('#inspectTab').classList.toggle('active', !markup); document.querySelector('#markupTab').classList.toggle('active', markup); document.querySelector('#inspectTab').setAttribute('aria-selected', String(!markup)); document.querySelector('#markupTab').setAttribute('aria-selected', String(markup)); if (markup) aside.scrollTop = 0; }
function open(rawValue, { reload = false } = {}) { if (!desktopBridge) return setStatus('Launch Page Tweaker.app. Opening src/index.html directly in a browser cannot inspect elements or export bundles.'); const source = reload ? state.source : utils.normalizeSource(rawValue); if (!source) return setStatus('Paste a file:// URL, public http(s) URL, or path to an .html file.'); const replacing = Boolean(state.source) && (reload || source !== state.source || hasSessionWork()); if (replacing && !window.confirm(`Load ${reload ? 'this page again' : 'the new page'}? This clears this page’s preview edits, pins, and markup.`)) { address.value = state.source; return; } clearSession(); state.source = source; address.value = source; document.querySelector('#empty').hidden = true; page.src = source; setStatus(reload ? 'Reloading a clean preview…' : 'Loading a fresh preview…'); }
function currentChanges() { return state.cssTweaks.get(state.selected.selector) || {}; }
function executeSelected(action, payload) { const id = `edit-${Date.now()}-${Math.random().toString(16).slice(2)}`; return new Promise((resolve, reject) => { const timeout = setTimeout(() => { pendingEdits.delete(id); reject(new Error('The page did not acknowledge the change. Select the element again.')); }, 1500); pendingEdits.set(id, { resolve, reject, timeout }); page.send('apply-edit', { id, action, targetId: state.selected.targetId, ...payload }); }); }
function setControlValues(style) { document.querySelectorAll('[data-style]').forEach((control) => { const property = control.dataset.style; const rawValue = utils.readableValue(style, property) || ''; if (control.tagName === 'SELECT') { control.value = currentChanges()[property] || ''; return; } if (control.type === 'color') { const match = rawValue.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/); control.value = match ? `#${[match[1], match[2], match[3]].map((value) => Number(value).toString(16).padStart(2, '0')).join('')}` : '#000000'; return; } const bounds = utils.sliderBounds(property, rawValue); control.min = bounds.min; control.max = bounds.max; control.step = bounds.step; control.value = bounds.value; control.nextElementSibling.value = bounds.value; }); }
function showSelection(selected) { selection.innerHTML = `<h2>Selected: ${selected.tag}</h2><p>${selected.text || 'No readable text'}</p><small>${selected.selector}</small>`; document.querySelector('#pinContext').textContent = `This note will stay attached to this ${selected.tag} while the page scrolls.`; }
function setAnnotationColor(color) { state.annotationColor = color; document.querySelectorAll('[data-color]').forEach((button) => button.classList.toggle('active', button.dataset.color === color)); }

page.addEventListener('did-finish-load', () => { page.send('set-inspector', !state.annotating); resizeCanvas(); setStatus('Click an element to inspect and tweak it.'); });
page.addEventListener('ipc-message', (_event) => { const [message] = _event.args; if (_event.channel === 'edit-result') { const pending = pendingEdits.get(message.id); if (!pending) return; clearTimeout(pending.timeout); pendingEdits.delete(message.id); message.ok ? pending.resolve() : pending.reject(new Error(message.message)); return; } if (_event.channel === 'element-position') { if (state.selected?.targetId === message.targetId) state.selected.box = message.box; state.notes.filter((note) => note.targetId === message.targetId).forEach((note) => { note.box = message.box; }); drawMarkup(); return; } if (_event.channel !== 'element-selected' || state.annotating) return; state.selected = message; if (!state.originalStyles.has(message.selector)) state.originalStyles.set(message.selector, message.inlineStyle); if (!state.originalTexts.has(message.selector)) state.originalTexts.set(message.selector, message.text); showSelection(message); controls.hidden = false; document.querySelector('#text').value = state.textChanges.get(message.selector) ?? message.text; setControlValues({ ...message.style, ...currentChanges() }); });

document.querySelectorAll('[data-style]').forEach((control) => control.addEventListener('input', async () => { if (!state.selected) return; const property = control.dataset.style; const rawValue = control.value; const value = utils.cssValue(property, rawValue); const changes = { ...currentChanges(), [property]: value }; if (property === 'font-family' && !rawValue) delete changes[property]; state.cssTweaks.set(state.selected.selector, changes); if (control.nextElementSibling?.tagName === 'OUTPUT') control.nextElementSibling.value = rawValue; try { await executeSelected('style', { changes }); setStatus(`Preview updated: ${property}.`); } catch (error) { setStatus(error.message); } }));
document.querySelectorAll('[data-reset-style]').forEach((button) => button.addEventListener('click', async () => { if (!state.selected) return; const property = button.dataset.resetStyle; const changes = { ...currentChanges() }; delete changes[property]; state.cssTweaks.set(state.selected.selector, changes); try { await executeSelected('reset-property', { property, value: state.selected.inlineProperties[property] }); setControlValues({ ...state.selected.style, ...changes }); setStatus(`Reset ${property} to its original value.`); } catch (error) { setStatus(error.message); } }));
document.querySelector('#applyText').addEventListener('click', async () => { if (!state.selected) return; const text = document.querySelector('#text').value; state.textChanges.set(state.selected.selector, text); try { await executeSelected('text', { text }); setStatus('Preview text updated.'); } catch (error) { setStatus(error.message); } });
document.querySelector('#pinNote').addEventListener('click', () => { const note = document.querySelector('#note').value.trim(); if (!state.selected || !note) return setStatus('Select an element and enter a note first.'); state.notes.push({ selector: state.selected.selector, targetId: state.selected.targetId, tag: state.selected.tag, text: state.selected.text, note, box: { ...state.selected.box } }); document.querySelector('#note').value = ''; renderNotes(); drawMarkup(); setStatus(`Pinned note ${state.notes.length} to the selected ${state.selected.tag}.`); });
document.querySelector('#reset').addEventListener('click', async () => { if (!state.selected) return; state.cssTweaks.delete(state.selected.selector); state.textChanges.delete(state.selected.selector); try { await executeSelected('restore', { inlineStyle: state.originalStyles.get(state.selected.selector), text: state.originalTexts.get(state.selected.selector) }); setControlValues(state.selected.style); document.querySelector('#text').value = state.originalTexts.get(state.selected.selector); setStatus('Selected preview overrides cleared.'); } catch (error) { setStatus(error.message); } });

document.querySelector('#open').addEventListener('click', () => open(address.value));
document.querySelector('#reload').addEventListener('click', () => { if (state.source) open(state.source, { reload: true }); else setStatus('Open a page before reloading.'); });
address.addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); open(address.value); } });
function openDropped(event) { event.preventDefault(); event.stopPropagation(); dropHint.hidden = true; const dropped = event.dataTransfer.getData('text/uri-list') || event.dataTransfer.getData('text/plain') || event.dataTransfer.files[0]?.path; if (dropped) open(dropped.split('\n')[0]); }
address.addEventListener('dragover', (event) => event.preventDefault()); address.addEventListener('drop', openDropped); stage.addEventListener('dragenter', (event) => { event.preventDefault(); dropHint.hidden = false; }); stage.addEventListener('dragover', (event) => event.preventDefault()); stage.addEventListener('dragleave', (event) => { if (!stage.contains(event.relatedTarget)) dropHint.hidden = true; }); stage.addEventListener('drop', openDropped); page.addEventListener('dragover', (event) => { event.preventDefault(); dropHint.hidden = false; }); page.addEventListener('drop', openDropped); document.body.addEventListener('dragover', (event) => event.preventDefault()); document.body.addEventListener('drop', (event) => { if (!stage.contains(event.target)) openDropped(event); });
document.querySelector('#file').addEventListener('click', async () => { if (!desktopBridge) return open(''); const picked = await desktopBridge.chooseSource(); if (picked) open(picked); });
function toggleAnnotate(active = !state.annotating) { state.annotating = active; canvas.style.pointerEvents = active ? 'auto' : 'none'; page.send('set-inspector', !active); document.querySelector('#annotate').classList.toggle('active', active); document.querySelector('#annotate').textContent = active ? '✓' : '✎'; setTab(active ? 'markup' : 'inspect'); setStatus(active ? 'Markup mode: choose a color and thickness, then draw over the page.' : 'Markup saved to this session.'); }
document.querySelector('#annotate').addEventListener('click', () => toggleAnnotate()); document.querySelector('#inspectTab').addEventListener('click', () => toggleAnnotate(false)); document.querySelector('#markupTab').addEventListener('click', () => toggleAnnotate(true)); document.querySelectorAll('[data-color]').forEach((button) => button.addEventListener('click', () => setAnnotationColor(button.dataset.color))); document.querySelector('#annotationThickness').addEventListener('input', (event) => { state.annotationWidth = Number(event.target.value); document.querySelector('#annotationThicknessValue').value = `${state.annotationWidth} px`; });
let stroke; canvas.addEventListener('pointerdown', (event) => { if (!state.annotating) return; stroke = { color: state.annotationColor, width: state.annotationWidth, points: [{ x: event.offsetX, y: event.offsetY }] }; canvas.setPointerCapture(event.pointerId); }); canvas.addEventListener('pointermove', (event) => { if (!stroke) return; stroke.points.push({ x: event.offsetX, y: event.offsetY }); drawMarkup(); ctx.strokeStyle = stroke.color; ctx.lineWidth = stroke.width; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); stroke.points.forEach((point, index) => index ? ctx.lineTo(point.x, point.y) : ctx.moveTo(point.x, point.y)); ctx.stroke(); }); canvas.addEventListener('pointerup', () => { if (stroke) state.strokes.push(stroke); stroke = null; });
async function captureScreenshot() { const timeout = new Promise((_, reject) => setTimeout(() => reject(new Error('Screenshot capture timed out.')), 1500)); const image = await Promise.race([page.capturePage(), timeout]); const base = `data:image/png;base64,${image.toPNG().toString('base64')}`; const imageElement = new Image(); await new Promise((resolve, reject) => { imageElement.onload = resolve; imageElement.onerror = reject; imageElement.src = base; }); const composite = document.createElement('canvas'); composite.width = imageElement.width; composite.height = imageElement.height; const compositeContext = composite.getContext('2d'); compositeContext.drawImage(imageElement, 0, 0); compositeContext.drawImage(canvas, 0, 0, composite.width, composite.height); return composite.toDataURL('image/png'); }
document.querySelector('#export').addEventListener('click', async () => { if (!desktopBridge) return setStatus('Launch Page Tweaker.app to export a bundle.'); if (!state.source) return setStatus('Open a page before exporting.'); const handoff = { version: 1, exportedAt: new Date().toISOString(), source: state.source, viewport: { width: page.clientWidth, height: page.clientHeight }, cssTweaks: [...state.cssTweaks].map(([selector, changes]) => ({ selector, changes })), textChanges: [...state.textChanges].map(([selector, text]) => ({ selector, text })), notes: state.notes, annotations: state.strokes }; let screenshot = null; try { screenshot = await captureScreenshot(); } catch { setStatus('Exporting bundle without a screenshot.'); } try { setStatus('Choose an export folder…'); const folder = await desktopBridge.exportBundle({ handoff, prompt: makePrompt(handoff), screenshot }); if (folder) { setStatus(`Bundle exported to ${folder}`); desktopBridge.showInFolder(folder); } else setStatus('Export canceled.'); } catch (error) { setStatus(`Export failed: ${error.message}`); } });
window.addEventListener('resize', resizeCanvas); page.setAttribute('preload', new URL('page-preload.cjs', location.href).href); const initial = new URLSearchParams(location.search).get('source'); if (initial) open(initial); if (desktopBridge) { desktopBridge.version().then((value) => { document.querySelector('#version').textContent = `v${value}`; }); desktopBridge.onOpenSource(open); } else setStatus('Launch Page Tweaker.app to open pages, select elements, pin notes, and export bundles.');
